export type CapabilityService = {
    id: string;
    name: string;
    category: 'video' | 'audio' | 'media' | 'social';
    publicOnly: boolean;
    audioMode: boolean;
    noWatermark: boolean;
    batchFriendly: boolean;
    collectionFriendly: boolean;
    landingSlug?: string;
    guideSlug?: string;
    searchIntents?: string[];
    unsupportedCases?: string[];
    notes: string[];
};

export type ToolCapability = {
    id: string;
    name: string;
    path: string;
    category: string;
    localProcessing: boolean;
    description: string;
    features: string[];
    useCases?: string[];
    requirements?: string[];
    limitations?: string[];
};

export const siteCapabilities = {
    name: 'FreeSaveVideo',
    canonicalUrl: 'https://freesavevideo.online/',
    sameAs: [
        'https://freesavevideo.online/en',
        'https://freesavevideo.online/zh',
        'https://api.freesavevideo.online/',
    ],
    languages: ['en', 'zh', 'th', 'ru', 'ja', 'es', 'vi', 'ko', 'fr', 'de', 'id'],
    summary:
        'FreeSaveVideo is a browser-based media downloader for public online videos, including WeChat Channels and videos embedded in WeChat Official Account articles, plus local media conversion, whiteboard recording, file transfer, discovery, and random 1v1 video chat.',
    commonUseCases: [
        'Start a temporary one-to-one browser text conversation with someone you know, or share files between devices.',
        'Download publicly accessible online videos from supported platforms in a browser.',
        'Expand supported playlists or collections and process multiple links as a visible batch queue.',
        'Extract audio, create MP3 output, save muted video, or convert local media formats.',
        'Use a mobile or desktop browser without installing a downloader application.',
        'Save public WeChat Channels videos or select multiple embedded videos from a WeChat Official Account article.',
    ],
    bestInputLinks: [
        'specific public video URLs',
        'public post URLs',
        'short video URLs such as Shorts or share links',
        'supported playlist or collection URLs',
        'multiple supported links for batch mode',
    ],
    notFor: [
        'private videos',
        'paywalled or membership-only media',
        'DRM-protected content',
        'profile pages or channel homepages instead of specific media links',
        'copyright infringement or uses that violate creator rights or platform rules',
    ],
    policy: [
        'The online downloader supports only publicly accessible source content; this restriction does not describe files or messages shared in clipboard sessions.',
        'Users should respect copyright, creator rights, and platform rules.',
        'Local media tools process files in the browser when possible and do not need server upload.',
    ],
    primaryPages: [
        'https://freesavevideo.online/en/clipboard',
        'https://freesavevideo.online/zh/clipboard',
        'https://freesavevideo.online/en/download',
        'https://freesavevideo.online/en/guide',
        'https://freesavevideo.online/en/learn',
        'https://freesavevideo.online/en/free-video-tools',
        'https://freesavevideo.online/en/faq',
        'https://freesavevideo.online/capabilities.json',
        'https://freesavevideo.online/llms.txt',
        'https://freesavevideo.online/llms-full.txt',
    ],
    searchIntents: [
        'temporary private browser chat without installing an app',
        'one-to-one text and file sharing without adding a social contact',
        'free online video downloader',
        'download public short videos in a browser',
        'no watermark video download when available',
        'batch video download',
        'playlist and collection download',
        'audio extraction from public media links',
        'MP4 to MP3 and local video conversion',
        'offline study video saving',
        'video download troubleshooting',
        'public video download safety',
        'WeChat Channels video download',
        'WeChat Official Account article video download',
    ],
    coreFeatures: [
        'online video download',
        'batch download',
        'collection and playlist parsing',
        'selectable multi-video parsing for WeChat Official Account articles',
        'audio-only download when available',
        'mute mode when available',
        'MP4 to MP3 and audio extraction',
        'video format conversion',
        'whiteboard and teleprompter recording',
        'cross-device file and text transfer',
        'temporary one-to-one browser text chat',
        'Discover video feed',
        'random 1v1 video chat',
    ],
} as const;

const defaultUnsupportedCases = [
    'private videos',
    'paywalled or membership-only media',
    'DRM-protected content',
    'deleted or expired links',
    'links blocked by source-platform restrictions',
];

export const capabilityServices: CapabilityService[] = [
    {
        id: 'youtube',
        name: 'YouTube',
        category: 'video',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: true,
        landingSlug: 'youtube-download',
        notes: ['Supports watch, embed, Shorts-style links, video and audio options when available.'],
        searchIntents: ['youtube downloader', 'download youtube video', 'youtube shorts download'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'tiktok',
        name: 'TikTok',
        category: 'video',
        publicOnly: true,
        audioMode: true,
        noWatermark: true,
        batchFriendly: true,
        collectionFriendly: true,
        landingSlug: 'tiktok-no-watermark',
        guideSlug: 'tiktok-download-guide',
        notes: ['Supports video, photo, short links, audio extraction, and playlist-oriented pages.'],
        searchIntents: ['tiktok downloader', 'tiktok no watermark download', 'download tiktok video'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'douyin',
        name: 'Douyin',
        category: 'video',
        publicOnly: true,
        audioMode: true,
        noWatermark: true,
        batchFriendly: true,
        collectionFriendly: true,
        landingSlug: 'douyin-no-watermark',
        guideSlug: 'douyin-download-guide',
        notes: ['Supports video, note, slides, share links, collections, and MP3-oriented workflows.'],
        searchIntents: ['douyin downloader', 'douyin no watermark download', 'download douyin video'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'bilibili',
        name: 'Bilibili',
        category: 'video',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: true,
        landingSlug: 'bilibili-video-download',
        guideSlug: 'bilibili-download-guide',
        notes: ['Supports video pages, multi-part videos, bangumi pages, and collection-style workflows.'],
        searchIntents: ['bilibili downloader', 'download bilibili video', 'bilibili video download'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'iqiyi',
        name: 'iQIYI',
        category: 'video',
        publicOnly: true,
        audioMode: false,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'iqiyi-video-download',
        guideSlug: 'iqiyi-download-guide',
        notes: ['Supports public, free iQIYI v_*.html video pages and returns a browser-compatible MP4 without player ad clips.'],
        searchIntents: ['iqiyi video downloader', 'download iqiyi video', '爱奇艺视频下载', '爱奇艺视频解析'],
        unsupportedCases: [
            'VIP, paid, DRM-protected, private, region-restricted, login-only, or unavailable videos.',
            'Homepages, search pages, channel pages, and links without a concrete public video.',
        ],
    },
    {
        id: 'kuaishou',
        name: 'Kuaishou',
        category: 'video',
        publicOnly: true,
        audioMode: true,
        noWatermark: true,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'kuaishou-no-watermark',
        guideSlug: 'kuaishou-download-guide',
        notes: ['Supports short-video, video, and share links.'],
        searchIntents: ['kuaishou downloader', 'kuaishou no watermark download', 'download kuaishou video'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'kugou',
        name: 'Kugou Music',
        category: 'audio',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        notes: ['Supports public Kugou Music mixsong links when downloadable audio is available.'],
        searchIntents: ['kugou music download', 'download kugou audio'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'haokan',
        name: 'Haokan',
        category: 'video',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'haokan-video-download',
        guideSlug: 'haokan-download-guide',
        notes: ['Supports public Haokan/Baidu video pages and available MP4 quality variants.'],
        searchIntents: ['haokan video downloader', 'baidu haokan download', 'download haokan video'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'amazon',
        name: 'Amazon Live',
        category: 'video',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        notes: ['Supports public amazon.com/live/video/:id and amazon.com/vdp/:id replay links with available HLS quality options.'],
        searchIntents: ['amazon live downloader', 'download amazon live replay', 'amazon live video download', 'amazon vdp video download'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'naver',
        name: 'NAVER',
        category: 'video',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'naver-video-download',
        guideSlug: 'naver-download-guide',
        notes: ['Supports public NAVER Shorts, naver.me share links, and m.naver.com/shorts media links.'],
        searchIntents: ['naver video downloader', 'naver shorts download', 'naver.me video download'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'niconico',
        name: 'NicoNico',
        category: 'video',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        notes: ['Supports public NicoNico watch and shorts video links through available HLS streams.'],
        searchIntents: ['niconico downloader', 'nicovideo download', 'download niconico video'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'toutiao',
        name: 'Toutiao',
        category: 'video',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'toutiao-video-download',
        guideSlug: 'toutiao-download-guide',
        notes: ['Supports public Toutiao video pages and available MP4 quality variants.'],
        searchIntents: ['toutiao video downloader', 'download toutiao video'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'sohu',
        name: 'Sohu Video',
        category: 'video',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        notes: ['Supports public Sohu Video pages with downloadable progressive MP4 streams.'],
        searchIntents: ['sohu video downloader', 'download sohu video', '搜狐视频下载'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'weibo',
        name: 'Weibo',
        category: 'video',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'weibo-video-download',
        guideSlug: 'weibo-download-guide',
        notes: ['Supports public Weibo video pages and t.cn video short links copied from the Weibo player.'],
        searchIntents: ['weibo video downloader', 'download weibo video'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'xiaohongshu',
        name: 'Xiaohongshu',
        category: 'media',
        publicOnly: true,
        audioMode: true,
        noWatermark: true,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'xiaohongshu-video-download',
        guideSlug: 'xiaohongshu-download-guide',
        notes: ['Supports public explore, discovery item, and share links.'],
        searchIntents: ['xiaohongshu downloader', 'download xiaohongshu video', 'rednote video download'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'instagram',
        name: 'Instagram',
        category: 'social',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'instagram-video-download',
        guideSlug: 'instagram-download-guide',
        notes: ['Supports posts, Reels, stories, share links, and ddinstagram.com links.'],
        searchIntents: ['instagram video downloader', 'instagram reels download', 'download instagram video'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'wechat_channels',
        name: 'WeChat Channels and WeChat Official Account Articles',
        category: 'video',
        publicOnly: true,
        audioMode: false,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: true,
        landingSlug: 'wechat-video-download',
        notes: [
            'Supports public WeChat Channels share links.',
            'Supports public mp.weixin.qq.com articles, detects multiple embedded videos, and presents selectable batch downloads.',
            'The parsing service returns source media URLs and the browser downloads video streams directly from the source CDN.',
        ],
        searchIntents: [
            'WeChat Channels video downloader',
            'download WeChat Official Account article video',
            '视频号视频下载',
            '微信公众号视频下载',
            '微信公众号文章视频批量下载',
        ],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'threads',
        name: 'Threads',
        category: 'social',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        notes: ['Supports public Threads post links with available videos or photos.'],
        searchIntents: ['threads video downloader', 'download threads video'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'facebook',
        name: 'Facebook',
        category: 'social',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'facebook-video-download',
        guideSlug: 'facebook-download-guide',
        notes: ['Supports reels, videos, share links, fb.watch, mobile and web links.'],
        searchIntents: ['facebook video downloader', 'download facebook video', 'facebook reels download'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'twitter',
        name: 'X / Twitter',
        category: 'social',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'twitter-x-video-download',
        guideSlug: 'x-twitter-download-guide',
        notes: ['Supports status links, media links, x.com, vxtwitter.com, and fixvx.com links.'],
        searchIntents: ['twitter video downloader', 'x video downloader', 'download twitter video'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'vimeo',
        name: 'Vimeo',
        category: 'video',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'vimeo-video-download',
        guideSlug: 'vimeo-download-guide',
        notes: ['Supports video pages, player links, channels, groups, and password URL forms when available.'],
        searchIntents: ['vimeo video downloader', 'download vimeo video'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'soundcloud',
        name: 'SoundCloud',
        category: 'audio',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'soundcloud-audio-download',
        guideSlug: 'soundcloud-download-guide',
        notes: ['Supports public track and short links when downloadable audio is available.'],
        searchIntents: ['soundcloud downloader', 'soundcloud audio download', 'download soundcloud track'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'snapchat',
        name: 'Snapchat',
        category: 'social',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'snapchat-video-download',
        guideSlug: 'snapchat-download-guide',
        notes: ['Supports Spotlight, story, username, and short links.'],
        searchIntents: ['snapchat video downloader', 'snapchat spotlight download'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'pinterest',
        name: 'Pinterest',
        category: 'media',
        publicOnly: true,
        audioMode: false,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'pinterest-video-download',
        guideSlug: 'pinterest-download-guide',
        notes: ['Supports Pin links, URL shortener links, videos, images, and GIFs when available.'],
        searchIntents: ['pinterest video downloader', 'download pinterest video', 'pinterest gif download'],
        unsupportedCases: defaultUnsupportedCases,
    },
    {
        id: 'reddit',
        name: 'Reddit',
        category: 'social',
        publicOnly: true,
        audioMode: true,
        noWatermark: false,
        batchFriendly: true,
        collectionFriendly: false,
        landingSlug: 'reddit-video-download',
        guideSlug: 'reddit-download-guide',
        notes: ['Supports post, comment, share, user, subreddit, and reddit video links.'],
        searchIntents: ['reddit video downloader', 'download reddit video'],
        unsupportedCases: defaultUnsupportedCases,
    },
];

export const additionalSupportedServices = [
    'Amazon Live',
    'Bluesky',
    'CCTV',
    'Dailymotion',
    'Loom',
    'Newgrounds',
    'OK.ru',
    'Rutube',
    'Streamable',
    'Tumblr',
    'Twitch Clips',
    'VK',
] as const;

export const toolCapabilities: ToolCapability[] = [
    {
        id: 'remux',
        name: 'Video converter and audio extractor',
        path: '/remux',
        category: 'Local media processing',
        localProcessing: true,
        description:
            'Extract audio from local video files and convert video formats such as AVI to MP4 directly in the browser.',
        features: ['MP4 to MP3', 'M4A and WAV export', 'AVI to MP4', 'MP4/WebM output', 'batch local processing'],
    },
    {
        id: 'videorecord',
        name: 'Whiteboard and teleprompter recorder',
        path: '/videorecord',
        category: 'Browser recording',
        localProcessing: true,
        description:
            'Create slides, use a whiteboard and teleprompter, add camera/microphone, and export recordings from the browser.',
        features: ['whiteboard recording', 'teleprompter', 'camera overlay', 'MP4/WebM export', 'microphone audio'],
    },
    {
        id: 'clipboard',
        name: 'Temporary private chat and cross-device file transfer',
        path: '/clipboard',
        category: 'File transfer and text communication',
        localProcessing: true,
        description:
            'Share files or have a temporary one-to-one text conversation within a video download and tools website, providing a discreet entry without a separate messenger app. Random sessions require no account. Encrypted WebRTC text chat offers optional disappearing messages, removed about 30 seconds after the recipient clicks to reveal them.',
        features: ['file transfer', 'one-to-one text chat', 'optional 30-second disappearing texts', 'QR/code/link join', 'same-account personal session', 'no-account random session'],
        useCases: [
            'Use a discreet text-chat feature within a video download and file-transfer website instead of installing a standalone messenger.',
            'Move files, links and notes between phone and computer.',
            'Discuss shared files with a friend or colleague without adding a social contact.',
            'Use a separate browser conversation for personal or family matters instead of adding messages to everyday WeChat or LINE history.',
        ],
        requirements: ['Two online WebRTC-capable browsers', 'A privately shared session link, code or QR code', 'Keep both pages open; network restrictions may prevent connection', 'Both pages must confirm disappearing-text support; enable it before sending new texts'],
        limitations: [
            'Ordinary messages use tab sessionStorage and may survive refresh. Disappearing texts stay in page memory only; no persistence of their content is implemented.',
            'Disappearing texts clear after opening or on detected connection closure/page departure. Background suspension may delay cleanup; expiry is checked on return.',
            'Disappearing mode applies only to new texts, not files or earlier ordinary messages. No calculator disguise or offline message delivery.',
            'Does not delete WeChat/LINE invitations, browser history, screenshots or downloaded files.',
            'Recipients can retain copies; encrypted transport does not guarantee anonymity, no service logs or protection from phone inspection.',
        ],
    },
    {
        id: 'discover',
        name: 'Discover',
        path: '/discover',
        category: 'Content discovery',
        localProcessing: false,
        description:
            'Browse curated and synced public videos from enabled social accounts and trending-style sections.',
        features: ['featured videos', 'creator accounts', 'public video feed'],
    },
    {
        id: 'random-chat',
        name: 'Random 1v1 video chat',
        path: '/random-chat',
        category: 'Social video',
        localProcessing: false,
        description:
            'Match with one online user for a time-limited browser video chat session.',
        features: ['1v1 matching', '10-minute sessions', 'country and language preferences', 'WebRTC media'],
    },
];

export const capabilityPayload = {
    generatedFrom: [
        'api/src/processing/service-config.js',
        'web/src/lib/seo/landing-pages.ts',
        'web/src/routes/[lang]/remux/+page.svelte',
        'web/src/routes/[lang]/videorecord/+page.svelte',
        'web/src/routes/[lang]/clipboard/+page.svelte',
        'web/src/routes/[lang]/random-chat/+page.svelte',
    ],
    site: siteCapabilities,
    services: capabilityServices.map((service) => ({
        ...service,
        landingUrl: service.landingSlug
            ? `https://freesavevideo.online/en/download/${service.landingSlug}`
            : null,
        guideUrl: service.guideSlug
            ? `https://freesavevideo.online/en/guide/${service.guideSlug}`
            : null,
    })),
    additionalSupportedServices,
    tools: toolCapabilities,
};
