import type { SeoLandingLocaleContent, SeoLandingPage } from './landing-pages';

type Copy = {
    title: string;
    description: string;
    keywords: string[];
    h1: string;
    lede: string;
    stepsTitle: string;
    steps: string[];
    featuresTitle: string;
    features: string[];
    faqTitle: string;
    faqs: Array<{ q: string; a: string }>;
    disclaimer: string;
};

const locale = (copy: Copy): SeoLandingLocaleContent => ({
    metaTitle: copy.title,
    metaDescription: copy.description,
    metaKeywords: copy.keywords,
    h1: copy.h1,
    lede: copy.lede,
    facts: copy.features.slice(0, 3),
    stepsTitle: copy.stepsTitle,
    steps: copy.steps,
    featuresTitle: copy.featuresTitle,
    features: copy.features,
    faqTitle: copy.faqTitle,
    faqs: copy.faqs,
    disclaimer: copy.disclaimer,
});

export const magnificLanding: SeoLandingPage = {
    slug: 'magnific-download',
    locales: {
        en: locale({
            title: 'Magnific Downloader for Free Images and Video Previews | FreeSaveVideo',
            description: 'Download public media exposed by free Magnific.com asset pages and compatible Magnific.ai links. Premium stock, private creations, Projects, and credit-based exports are excluded.',
            keywords: ['Magnific downloader', 'Magnific image downloader', 'Magnific video downloader', 'magnific.com download', 'magnific.ai downloader'],
            h1: 'Magnific Free Media Downloader',
            lede: 'Save public images and available video previews from Magnific pages explicitly marked free, plus compatible direct media links from Magnific.com and legacy Magnific.ai. Paid and private content is never unlocked.',
            stepsTitle: 'How to download free Magnific media',
            steps: ['Open one public Magnific asset page whose URL begins with free-, and confirm its license and attribution requirements.', 'Paste the page URL into FreeSaveVideo. If Magnific blocks server access, open the same page in Chrome or Edge.', 'For the browser route, play a free video if needed and scan the page with the FreeSaveVideo extension.', 'Choose the public image or video preview that the source page exposes and save it in your browser.'],
            featuresTitle: 'Supported Magnific content and limits',
            features: ['Supports public free photo, free AI image, vector/PSD preview, and free stock-video pages.', 'Supports direct public image, video, and audio media URLs on Magnific CDN subdomains and legacy magnific.ai asset URLs.', 'Magnific.com is the renamed Freepik platform; magnific.ai remains the legacy upscaler service for existing users.', 'Premium stock, private AI creations, Projects, login-only files, original vector/PSD packages, and credit-based exports are not supported.', 'Free assets can require creator attribution. FreeSaveVideo does not issue a Magnific license or bypass its account and daily-download rules.'],
            faqTitle: 'Magnific download FAQ',
            faqs: [
                { q: 'Is Magnific.com the same as Magnific.ai?', a: 'Magnific.com is the renamed Freepik creative platform. Magnific.ai remains a separate legacy upscaler for existing accounts, and compatible public asset links from both domains are recognized.' },
                { q: 'Which Magnific downloads are supported?', a: 'Public media exposed by URLs explicitly marked free: photos, AI images, image previews for vectors or PSDs, and available stock-video previews. Direct public Magnific media URLs are also accepted.' },
                { q: 'Can FreeSaveVideo download Premium Magnific assets?', a: 'No. Premium stock, paid formats, subscription downloads, and credit-based AI exports are intentionally excluded.' },
                { q: 'Why might I need the browser extension?', a: 'Magnific can block server-side page requests. The extension reads only media already exposed in the public free page you opened; it does not log in or bypass access controls.' },
                { q: 'Do free Magnific files require attribution?', a: 'Often yes. Check the asset page and Magnific license. FreeSaveVideo saves available media but does not replace the source license or attribution notice.' },
            ],
            disclaimer: 'Download only public free media you are allowed to use. Follow the asset license, attribution terms, copyright law, and Magnific rules.',
        }),
        zh: locale({
            title: 'Magnific 免费图片与视频预览下载器 | FreeSaveVideo',
            description: '下载 Magnific.com 明确标记为免费的公开图片和视频预览，并兼容 Magnific.ai 旧版公开资源链接。不支持 Premium、私有创作、Projects 或积分导出。',
            keywords: ['Magnific 下载器', 'Magnific 图片下载', 'Magnific 视频下载', 'magnific.com 下载', 'magnific.ai 下载'],
            h1: 'Magnific 免费媒体下载器',
            lede: '保存 Magnific 免费素材页公开提供的图片和视频预览，也兼容 Magnific.com 与旧版 Magnific.ai 的公开媒体直链；不会解锁付费或私有内容。',
            stepsTitle: '如何下载 Magnific 免费媒体',
            steps: ['打开 URL 中明确带有 free- 的公开素材页，并先确认许可证与署名要求。', '把素材页地址粘贴到 FreeSaveVideo；若 Magnific 拦截服务器访问，请在 Chrome 或 Edge 打开原页面。', '使用浏览器扩展时，免费的视频页面可能需要先播放，再扫描当前页面。', '选择源页面公开提供的图片或视频预览，并通过浏览器保存。'],
            featuresTitle: 'Magnific 支持范围与限制',
            features: ['支持公开的免费照片、免费 AI 图片、矢量/PSD 预览和免费 stock 视频页面。', '支持 Magnific CDN 子域上的公开图片、视频、音频直链，以及旧版 magnific.ai 资源链接。', 'Magnific.com 是原 Freepik 更名后的平台；magnific.ai 仍为现有用户保留旧版放大器服务。', '不支持 Premium 素材、私有 AI 创作、Projects、仅登录可见文件、矢量/PSD 原始包或需要积分的导出。', '免费素材可能要求署名；FreeSaveVideo 不签发 Magnific 许可证，也不绕过账号和每日下载规则。'],
            faqTitle: 'Magnific 下载常见问题',
            faqs: [
                { q: 'Magnific.com 和 Magnific.ai 是同一个平台吗？', a: 'Magnific.com 是原 Freepik 更名后的综合创意平台；Magnific.ai 是为现有账户保留的旧版放大器。两者兼容的公开资源链接均可识别。' },
                { q: '可以下载哪些 Magnific 内容？', a: '支持 URL 明确标记为免费的公开照片、AI 图片、矢量或 PSD 的图片预览，以及可用的 stock 视频预览；也支持公开媒体直链。' },
                { q: '可以下载 Magnific Premium 素材吗？', a: '不可以。我们明确排除 Premium、付费格式、订阅下载和消耗积分的 AI 导出。' },
                { q: '为什么有时需要浏览器扩展？', a: 'Magnific 可能阻止服务器读取页面。扩展只读取你已打开的公开免费页面中已经暴露的媒体，不会登录或绕过访问控制。' },
                { q: 'Magnific 免费素材需要署名吗？', a: '通常需要。请查看素材页和 Magnific 许可证；FreeSaveVideo 只保存可用媒体，不能替代许可证或署名说明。' },
            ],
            disclaimer: '只下载你有权使用的公开免费媒体，并遵守素材许可证、署名要求、版权法和 Magnific 规则。',
        }),
        de: locale({
            title: 'Magnific Downloader für kostenlose Bilder und Videovorschauen | FreeSaveVideo',
            description: 'Öffentliche Medien von kostenlosen Magnific.com-Seiten und kompatiblen Magnific.ai-Links speichern. Premium-Inhalte, private Kreationen und Credit-Exporte sind ausgeschlossen.',
            keywords: ['Magnific Downloader', 'Magnific Bilder herunterladen', 'Magnific Video Downloader', 'magnific.com Download'],
            h1: 'Magnific Downloader für kostenlose Medien',
            lede: 'Speichere öffentliche Bilder und verfügbare Videovorschauen von ausdrücklich kostenlosen Magnific-Seiten. Bezahlte oder private Inhalte werden nicht entsperrt.',
            stepsTitle: 'Kostenlose Magnific-Medien herunterladen',
            steps: ['Öffne eine öffentliche Magnific-Seite mit free- in der URL und prüfe Lizenz sowie Namensnennung.', 'Füge die URL in FreeSaveVideo ein; bei einer Serversperre öffnest du die Seite in Chrome oder Edge.', 'Starte kostenlose Videos bei Bedarf und scanne die Seite mit der FreeSaveVideo-Erweiterung.', 'Wähle das öffentlich bereitgestellte Bild oder die Videovorschau und speichere sie im Browser.'],
            featuresTitle: 'Unterstützte Inhalte und Grenzen',
            features: ['Unterstützt kostenlose Fotos, KI-Bilder, Vektor-/PSD-Vorschauen und kostenlose Stockvideo-Seiten.', 'Direkte öffentliche Medien-URLs auf Magnific-CDNs und ältere magnific.ai-Asset-Links werden erkannt.', 'Magnific.com ist die umbenannte Freepik-Plattform; magnific.ai bleibt der ältere Upscaler.', 'Premium-Stock, private Kreationen, Projects, Originalpakete und Credit-Exporte werden nicht unterstützt.', 'Kostenlose Assets können eine Namensnennung verlangen; Kontingente und Lizenzen werden nicht umgangen.'],
            faqTitle: 'FAQ zum Magnific-Download',
            faqs: [{ q: 'Was ist Magnific.com?', a: 'Es ist die umbenannte Freepik-Kreativplattform; magnific.ai bleibt der ältere Upscaler.' }, { q: 'Welche Inhalte werden unterstützt?', a: 'Öffentliche Medien von ausdrücklich kostenlosen Asset-Seiten und direkte öffentliche Magnific-Medienlinks.' }, { q: 'Werden Premium-Assets unterstützt?', a: 'Nein. Bezahlte Inhalte, Abonnementdownloads und Credit-Exporte sind ausgeschlossen.' }, { q: 'Warum wird eine Erweiterung benötigt?', a: 'Sie liest Medien aus der bereits geöffneten kostenlosen Seite, wenn Magnific Serverzugriffe blockiert.' }, { q: 'Ist eine Namensnennung nötig?', a: 'Oft ja. Prüfe immer die Magnific-Lizenz der Ressource.' }],
            disclaimer: 'Lade nur erlaubte öffentliche Gratis-Medien herunter und beachte Lizenz, Urheberrecht und Plattformregeln.',
        }),
        es: locale({
            title: 'Descargador de Magnific para imágenes gratis y vistas previas de vídeo | FreeSaveVideo',
            description: 'Guarda medios públicos de páginas gratuitas de Magnific.com y enlaces compatibles de Magnific.ai. Se excluyen recursos Premium, creaciones privadas y exportaciones con créditos.',
            keywords: ['descargador Magnific', 'descargar imágenes Magnific', 'descargar vídeos Magnific', 'magnific.com descargar'],
            h1: 'Descargador de medios gratuitos de Magnific',
            lede: 'Guarda imágenes públicas y vistas previas de vídeo disponibles en páginas de Magnific marcadas como gratuitas. No desbloquea contenido privado ni de pago.',
            stepsTitle: 'Cómo descargar medios gratuitos de Magnific',
            steps: ['Abre una página pública con free- en la URL y revisa su licencia y atribución.', 'Pega la URL en FreeSaveVideo; si Magnific bloquea el servidor, abre la página en Chrome o Edge.', 'Si es un vídeo, reprodúcelo y analiza la página con la extensión FreeSaveVideo.', 'Elige la imagen o vista previa pública y guárdala con el navegador.'],
            featuresTitle: 'Contenido compatible y límites',
            features: ['Admite fotos gratis, imágenes de IA gratis, vistas previas de vectores/PSD y vídeos stock gratis.', 'Reconoce enlaces públicos directos de CDN de Magnific y recursos antiguos de magnific.ai.', 'Magnific.com es la plataforma antes llamada Freepik; magnific.ai sigue siendo el escalador heredado.', 'No admite Premium, creaciones privadas, Projects, paquetes originales ni exportaciones con créditos.', 'Los recursos gratuitos pueden exigir atribución; no se eluden licencias, cuentas ni límites diarios.'],
            faqTitle: 'Preguntas sobre descargas de Magnific',
            faqs: [{ q: '¿Qué es Magnific.com?', a: 'Es la plataforma creativa antes llamada Freepik; magnific.ai conserva el escalador heredado.' }, { q: '¿Qué se puede descargar?', a: 'Medios públicos de páginas marcadas como gratuitas y enlaces directos públicos de Magnific.' }, { q: '¿Se admite contenido Premium?', a: 'No. Se excluyen recursos de pago, descargas por suscripción y exportaciones con créditos.' }, { q: '¿Por qué usar la extensión?', a: 'Lee los medios de la página gratuita ya abierta cuando Magnific bloquea el acceso del servidor.' }, { q: '¿Debo atribuir al autor?', a: 'A menudo sí. Consulta siempre la licencia del recurso en Magnific.' }],
            disclaimer: 'Descarga solo medios gratuitos que puedas usar y respeta la licencia, la atribución y los derechos de autor.',
        }),
        fr: locale({
            title: 'Téléchargeur Magnific pour images gratuites et aperçus vidéo | FreeSaveVideo',
            description: 'Enregistrez les médias publics des pages gratuites Magnific.com et les liens Magnific.ai compatibles. Les contenus Premium, privés et exports payants sont exclus.',
            keywords: ['téléchargeur Magnific', 'télécharger image Magnific', 'télécharger vidéo Magnific', 'magnific.com téléchargement'],
            h1: 'Téléchargeur de médias gratuits Magnific',
            lede: 'Enregistrez les images publiques et les aperçus vidéo disponibles sur les pages Magnific explicitement gratuites, sans déverrouiller de contenu payant ou privé.',
            stepsTitle: 'Comment télécharger un média Magnific gratuit',
            steps: ['Ouvrez une page publique contenant free- dans son URL et vérifiez la licence.', 'Collez l’URL dans FreeSaveVideo ; si Magnific bloque le serveur, ouvrez la page dans Chrome ou Edge.', 'Pour une vidéo gratuite, lancez-la puis analysez la page avec l’extension FreeSaveVideo.', 'Choisissez l’image ou l’aperçu vidéo public et enregistrez-le dans le navigateur.'],
            featuresTitle: 'Contenu pris en charge et limites',
            features: ['Prend en charge photos gratuites, images IA, aperçus vectoriels/PSD et vidéos stock gratuites.', 'Reconnaît les URL publiques des CDN Magnific et les anciens liens d’assets magnific.ai.', 'Magnific.com est la plateforme auparavant appelée Freepik ; magnific.ai reste l’ancien upscaler.', 'Exclut Premium, créations privées, Projects, archives originales et exports consommant des crédits.', 'Une attribution peut être requise ; les licences, comptes et quotas ne sont pas contournés.'],
            faqTitle: 'FAQ du téléchargement Magnific',
            faqs: [{ q: 'Qu’est-ce que Magnific.com ?', a: 'C’est la plateforme créative auparavant appelée Freepik ; magnific.ai conserve l’ancien upscaler.' }, { q: 'Quels contenus sont compatibles ?', a: 'Les médias publics des pages explicitement gratuites et les liens médias publics directs.' }, { q: 'Les contenus Premium sont-ils pris en charge ?', a: 'Non. Les ressources payantes et exports à crédits sont exclus.' }, { q: 'Pourquoi utiliser l’extension ?', a: 'Elle lit les médias de la page gratuite déjà ouverte lorsque Magnific bloque les serveurs.' }, { q: 'Faut-il créditer l’auteur ?', a: 'Souvent oui. Consultez toujours la licence Magnific de la ressource.' }],
            disclaimer: 'Téléchargez uniquement les médias gratuits autorisés et respectez licence, attribution et droits d’auteur.',
        }),
        ja: locale({
            title: 'Magnific 無料画像・動画プレビュー ダウンローダー | FreeSaveVideo',
            description: 'Magnific.com の無料公開ページと互換性のある Magnific.ai リンクから公開メディアを保存。Premium、非公開作品、クレジット利用の書き出しは対象外です。',
            keywords: ['Magnific ダウンローダー', 'Magnific 画像 ダウンロード', 'Magnific 動画 ダウンロード', 'magnific.com 保存'],
            h1: 'Magnific 無料メディア ダウンローダー',
            lede: '無料と明記された Magnific ページの公開画像と利用可能な動画プレビューを保存します。有料・非公開コンテンツは解除しません。',
            stepsTitle: 'Magnific の無料メディアを保存する方法',
            steps: ['URL に free- を含む公開ページを開き、ライセンスとクレジット表記を確認します。', 'URL を FreeSaveVideo に貼り付けます。サーバーが拒否された場合は Chrome または Edge で開きます。', '無料動画は必要に応じて再生し、FreeSaveVideo 拡張機能でページをスキャンします。', '公開されている画像または動画プレビューを選び、ブラウザーで保存します。'],
            featuresTitle: '対応コンテンツと制限',
            features: ['無料写真、無料 AI 画像、ベクター/PSD のプレビュー、無料ストック動画ページに対応します。', 'Magnific CDN の公開直リンクと旧 magnific.ai アセットリンクを認識します。', 'Magnific.com は旧 Freepik、magnific.ai は既存ユーザー向け旧アップスケーラーです。', 'Premium、非公開作品、Projects、元データ一式、クレジット書き出しには対応しません。', '無料素材でも帰属表示が必要な場合があり、アカウントや上限、ライセンスは回避しません。'],
            faqTitle: 'Magnific ダウンロード FAQ',
            faqs: [{ q: 'Magnific.com とは？', a: '旧 Freepik のクリエイティブプラットフォームです。magnific.ai は旧アップスケーラーとして残っています。' }, { q: '何を保存できますか？', a: '無料と明記されたページの公開メディアと、Magnific の公開メディア直リンクです。' }, { q: 'Premium 素材に対応しますか？', a: 'いいえ。有料素材、購読ダウンロード、クレジット書き出しは対象外です。' }, { q: '拡張機能が必要なのはなぜ？', a: 'サーバーアクセスが拒否された場合、開いている無料ページ内の公開メディアを読み取るためです。' }, { q: '帰属表示は必要ですか？', a: '必要な場合があります。必ず Magnific の素材ライセンスを確認してください。' }],
            disclaimer: '利用権のある無料公開メディアのみ保存し、ライセンス、帰属表示、著作権を守ってください。',
        }),
        ko: locale({
            title: 'Magnific 무료 이미지 및 동영상 미리보기 다운로더 | FreeSaveVideo',
            description: 'Magnific.com 무료 공개 페이지와 호환되는 Magnific.ai 링크의 미디어를 저장합니다. Premium, 비공개 작업물, 크레딧 내보내기는 제외됩니다.',
            keywords: ['Magnific 다운로더', 'Magnific 이미지 다운로드', 'Magnific 동영상 다운로드', 'magnific.com 다운로드'],
            h1: 'Magnific 무료 미디어 다운로더',
            lede: '무료로 명시된 Magnific 페이지의 공개 이미지와 동영상 미리보기를 저장합니다. 유료 또는 비공개 콘텐츠를 해제하지 않습니다.',
            stepsTitle: 'Magnific 무료 미디어 다운로드 방법',
            steps: ['URL에 free-가 있는 공개 페이지를 열고 라이선스와 출처 표시 조건을 확인하세요.', 'URL을 FreeSaveVideo에 붙여 넣고 서버가 차단되면 Chrome 또는 Edge에서 페이지를 여세요.', '무료 동영상은 필요하면 재생한 뒤 FreeSaveVideo 확장 프로그램으로 페이지를 스캔하세요.', '페이지에 공개된 이미지나 동영상 미리보기를 골라 브라우저에 저장하세요.'],
            featuresTitle: '지원 범위와 제한',
            features: ['무료 사진, AI 이미지, 벡터/PSD 미리보기, 무료 스톡 동영상 페이지를 지원합니다.', 'Magnific CDN 공개 직링크와 기존 magnific.ai 자산 링크를 인식합니다.', 'Magnific.com은 이전 Freepik 플랫폼이며 magnific.ai는 기존 업스케일러입니다.', 'Premium, 비공개 작업물, Projects, 원본 패키지, 크레딧 내보내기는 지원하지 않습니다.', '무료 자산도 출처 표시가 필요할 수 있으며 계정, 한도, 라이선스를 우회하지 않습니다.'],
            faqTitle: 'Magnific 다운로드 FAQ',
            faqs: [{ q: 'Magnific.com은 무엇인가요?', a: '이전 Freepik 크리에이티브 플랫폼이며 magnific.ai는 기존 업스케일러로 남아 있습니다.' }, { q: '무엇을 다운로드할 수 있나요?', a: '무료라고 명시된 페이지의 공개 미디어와 Magnific 공개 미디어 직링크입니다.' }, { q: 'Premium 자산도 지원하나요?', a: '아니요. 유료 자산과 구독 또는 크레딧 내보내기는 제외됩니다.' }, { q: '왜 확장 프로그램이 필요한가요?', a: 'Magnific이 서버 접근을 막을 때 이미 열린 무료 페이지의 공개 미디어를 읽기 위해서입니다.' }, { q: '출처 표시가 필요한가요?', a: '필요할 수 있습니다. 항상 Magnific 자산 라이선스를 확인하세요.' }],
            disclaimer: '사용 권한이 있는 무료 공개 미디어만 저장하고 라이선스와 저작권을 준수하세요.',
        }),
        ru: locale({
            title: 'Загрузчик Magnific для бесплатных изображений и превью видео | FreeSaveVideo',
            description: 'Сохраняйте публичные медиа с бесплатных страниц Magnific.com и совместимых ссылок Magnific.ai. Premium, приватные работы и платный экспорт не поддерживаются.',
            keywords: ['Magnific скачать', 'Magnific загрузчик изображений', 'Magnific видео скачать', 'magnific.com downloader'],
            h1: 'Загрузчик бесплатных медиа Magnific',
            lede: 'Сохраняйте публичные изображения и доступные превью видео со страниц Magnific, явно отмеченных как бесплатные. Платный и приватный контент не открывается.',
            stepsTitle: 'Как скачать бесплатное медиа Magnific',
            steps: ['Откройте публичную страницу с free- в URL и проверьте лицензию и атрибуцию.', 'Вставьте URL в FreeSaveVideo; при блокировке сервера откройте страницу в Chrome или Edge.', 'При необходимости запустите бесплатное видео и просканируйте страницу расширением FreeSaveVideo.', 'Выберите публичное изображение или превью видео и сохраните его в браузере.'],
            featuresTitle: 'Поддержка и ограничения',
            features: ['Поддерживаются бесплатные фото, AI-изображения, превью векторов/PSD и бесплатные stock-видео.', 'Распознаются публичные CDN-ссылки Magnific и старые ресурсы magnific.ai.', 'Magnific.com — новое имя платформы Freepik; magnific.ai остаётся прежним апскейлером.', 'Premium, приватные работы, Projects, исходные пакеты и экспорт за кредиты исключены.', 'Для бесплатных материалов может требоваться атрибуция; аккаунты, лимиты и лицензии не обходятся.'],
            faqTitle: 'FAQ по загрузке Magnific',
            faqs: [{ q: 'Что такое Magnific.com?', a: 'Это новое имя творческой платформы Freepik; magnific.ai остаётся прежним апскейлером.' }, { q: 'Что можно скачать?', a: 'Публичные медиа со страниц, явно помеченных бесплатными, и прямые публичные ссылки Magnific.' }, { q: 'Поддерживается Premium?', a: 'Нет. Платные ресурсы и экспорт за кредиты исключены.' }, { q: 'Зачем нужно расширение?', a: 'Оно читает медиа с уже открытой бесплатной страницы, когда Magnific блокирует сервер.' }, { q: 'Нужна ли атрибуция?', a: 'Часто да. Всегда проверяйте лицензию ресурса Magnific.' }],
            disclaimer: 'Скачивайте только разрешённые бесплатные медиа и соблюдайте лицензию и авторские права.',
        }),
        th: locale({
            title: 'เครื่องมือดาวน์โหลด Magnific สำหรับรูปฟรีและตัวอย่างวิดีโอ | FreeSaveVideo',
            description: 'บันทึกสื่อสาธารณะจากหน้าฟรีของ Magnific.com และลิงก์ Magnific.ai ที่รองรับ ไม่รองรับ Premium งานส่วนตัว หรือการส่งออกที่ใช้เครดิต',
            keywords: ['ดาวน์โหลด Magnific', 'ดาวน์โหลดรูป Magnific', 'ดาวน์โหลดวิดีโอ Magnific', 'magnific.com downloader'],
            h1: 'เครื่องมือดาวน์โหลดสื่อฟรีจาก Magnific',
            lede: 'บันทึกรูปสาธารณะและตัวอย่างวิดีโอที่มีในหน้า Magnific ซึ่งระบุว่าฟรี โดยไม่ปลดล็อกเนื้อหาแบบชำระเงินหรือส่วนตัว',
            stepsTitle: 'วิธีดาวน์โหลดสื่อฟรีจาก Magnific',
            steps: ['เปิดหน้าสาธารณะที่มี free- ใน URL และตรวจสอบใบอนุญาตกับข้อกำหนดการให้เครดิต', 'วาง URL ใน FreeSaveVideo หาก Magnific บล็อกเซิร์ฟเวอร์ ให้เปิดหน้าเดิมใน Chrome หรือ Edge', 'สำหรับวิดีโอฟรี ให้เล่นก่อนหากจำเป็น แล้วสแกนหน้าด้วยส่วนขยาย FreeSaveVideo', 'เลือกภาพหรือตัวอย่างวิดีโอที่หน้าเผยแพร่และบันทึกผ่านเบราว์เซอร์'],
            featuresTitle: 'ขอบเขตที่รองรับและข้อจำกัด',
            features: ['รองรับภาพถ่ายฟรี ภาพ AI ฟรี ตัวอย่างเวกเตอร์/PSD และหน้าวิดีโอ stock ฟรี', 'รองรับลิงก์สื่อสาธารณะจาก CDN ของ Magnific และลิงก์ assets เดิมของ magnific.ai', 'Magnific.com คือแพลตฟอร์มเดิมชื่อ Freepik ส่วน magnific.ai คือ upscaler รุ่นเดิม', 'ไม่รองรับ Premium งานส่วนตัว Projects แพ็กเกจต้นฉบับ หรือการส่งออกที่ใช้เครดิต', 'สื่อฟรีอาจต้องให้เครดิต และจะไม่ข้ามบัญชี โควตา หรือใบอนุญาต'],
            faqTitle: 'คำถามที่พบบ่อยเกี่ยวกับ Magnific',
            faqs: [{ q: 'Magnific.com คืออะไร?', a: 'คือแพลตฟอร์มสร้างสรรค์ที่เดิมชื่อ Freepik ส่วน magnific.ai ยังคงเป็น upscaler รุ่นเดิม' }, { q: 'ดาวน์โหลดอะไรได้บ้าง?', a: 'สื่อสาธารณะจากหน้าที่ระบุว่าฟรีและลิงก์สื่อสาธารณะโดยตรงของ Magnific' }, { q: 'รองรับ Premium หรือไม่?', a: 'ไม่รองรับสื่อแบบชำระเงินและการส่งออกที่ใช้เครดิต' }, { q: 'ทำไมต้องใช้ส่วนขยาย?', a: 'เพื่ออ่านสื่อจากหน้าฟรีที่เปิดอยู่เมื่อ Magnific บล็อกเซิร์ฟเวอร์' }, { q: 'ต้องให้เครดิตหรือไม่?', a: 'อาจต้องให้เครดิต โปรดตรวจสอบใบอนุญาตของ Magnific ทุกครั้ง' }],
            disclaimer: 'ดาวน์โหลดเฉพาะสื่อฟรีที่คุณมีสิทธิ์ใช้ และปฏิบัติตามใบอนุญาตกับลิขสิทธิ์',
        }),
        vi: locale({
            title: 'Trình tải Magnific cho ảnh miễn phí và bản xem trước video | FreeSaveVideo',
            description: 'Lưu nội dung công khai từ trang miễn phí Magnific.com và liên kết Magnific.ai tương thích. Không hỗ trợ Premium, tác phẩm riêng tư hoặc xuất bằng tín dụng.',
            keywords: ['tải Magnific', 'tải ảnh Magnific', 'tải video Magnific', 'magnific.com downloader'],
            h1: 'Trình tải nội dung miễn phí Magnific',
            lede: 'Lưu ảnh công khai và bản xem trước video có sẵn trên các trang Magnific được đánh dấu miễn phí, không mở khóa nội dung trả phí hay riêng tư.',
            stepsTitle: 'Cách tải nội dung Magnific miễn phí',
            steps: ['Mở trang công khai có free- trong URL và kiểm tra giấy phép cùng yêu cầu ghi nguồn.', 'Dán URL vào FreeSaveVideo; nếu Magnific chặn máy chủ, hãy mở trang trong Chrome hoặc Edge.', 'Với video miễn phí, phát video nếu cần rồi quét trang bằng tiện ích FreeSaveVideo.', 'Chọn ảnh hoặc bản xem trước video công khai và lưu bằng trình duyệt.'],
            featuresTitle: 'Nội dung hỗ trợ và giới hạn',
            features: ['Hỗ trợ ảnh miễn phí, ảnh AI, bản xem trước vector/PSD và trang video stock miễn phí.', 'Nhận dạng liên kết CDN công khai của Magnific và asset cũ từ magnific.ai.', 'Magnific.com là nền tảng trước đây mang tên Freepik; magnific.ai là trình nâng cấp ảnh cũ.', 'Không hỗ trợ Premium, tác phẩm riêng tư, Projects, gói gốc hoặc xuất bằng tín dụng.', 'Nội dung miễn phí có thể yêu cầu ghi nguồn; không vượt qua tài khoản, hạn mức hay giấy phép.'],
            faqTitle: 'Câu hỏi về tải Magnific',
            faqs: [{ q: 'Magnific.com là gì?', a: 'Đây là nền tảng sáng tạo trước đây mang tên Freepik; magnific.ai vẫn là trình nâng cấp ảnh cũ.' }, { q: 'Có thể tải gì?', a: 'Nội dung công khai từ trang được đánh dấu miễn phí và liên kết media công khai trực tiếp.' }, { q: 'Có hỗ trợ Premium không?', a: 'Không. Nội dung trả phí và xuất bằng tín dụng bị loại trừ.' }, { q: 'Vì sao cần tiện ích?', a: 'Tiện ích đọc media trên trang miễn phí đã mở khi Magnific chặn máy chủ.' }, { q: 'Có cần ghi nguồn không?', a: 'Thường là có. Hãy luôn kiểm tra giấy phép Magnific của tài nguyên.' }],
            disclaimer: 'Chỉ tải nội dung miễn phí mà bạn có quyền sử dụng và tuân thủ giấy phép cùng bản quyền.',
        }),
        id: locale({
            title: 'Pengunduh Magnific untuk gambar gratis dan pratinjau video | FreeSaveVideo',
            description: 'Simpan media publik dari halaman gratis Magnific.com dan tautan Magnific.ai yang kompatibel. Premium, karya privat, dan ekspor berbasis kredit tidak didukung.',
            keywords: ['pengunduh Magnific', 'unduh gambar Magnific', 'unduh video Magnific', 'magnific.com download'],
            h1: 'Pengunduh media gratis Magnific',
            lede: 'Simpan gambar publik dan pratinjau video yang tersedia pada halaman Magnific yang jelas ditandai gratis, tanpa membuka konten berbayar atau privat.',
            stepsTitle: 'Cara mengunduh media Magnific gratis',
            steps: ['Buka halaman publik dengan free- pada URL lalu periksa lisensi dan atribusinya.', 'Tempel URL ke FreeSaveVideo; jika Magnific memblokir server, buka halaman di Chrome atau Edge.', 'Untuk video gratis, putar bila perlu lalu pindai halaman dengan ekstensi FreeSaveVideo.', 'Pilih gambar atau pratinjau video publik lalu simpan melalui browser.'],
            featuresTitle: 'Konten yang didukung dan batasan',
            features: ['Mendukung foto gratis, gambar AI, pratinjau vektor/PSD, dan halaman video stok gratis.', 'Mengenali tautan CDN publik Magnific dan aset lama magnific.ai.', 'Magnific.com adalah platform yang sebelumnya bernama Freepik; magnific.ai adalah upscaler lama.', 'Tidak mendukung Premium, karya privat, Projects, paket asli, atau ekspor berbasis kredit.', 'Aset gratis mungkin memerlukan atribusi; akun, kuota, dan lisensi tidak dilewati.'],
            faqTitle: 'FAQ unduhan Magnific',
            faqs: [{ q: 'Apa itu Magnific.com?', a: 'Platform kreatif yang sebelumnya bernama Freepik; magnific.ai tetap menjadi upscaler lama.' }, { q: 'Apa yang dapat diunduh?', a: 'Media publik dari halaman yang ditandai gratis dan tautan media publik langsung.' }, { q: 'Apakah Premium didukung?', a: 'Tidak. Aset berbayar dan ekspor berbasis kredit dikecualikan.' }, { q: 'Mengapa perlu ekstensi?', a: 'Ekstensi membaca media dari halaman gratis yang sudah dibuka saat Magnific memblokir server.' }, { q: 'Apakah atribusi diperlukan?', a: 'Sering kali ya. Selalu periksa lisensi aset Magnific.' }],
            disclaimer: 'Unduh hanya media gratis yang boleh Anda gunakan dan patuhi lisensi serta hak cipta.',
        }),
    },
    supportedLinkFormats: [
        'magnific.com/free-photo/…',
        'magnific.com/free-ai-image/…',
        'magnific.com/free-vector/…',
        'magnific.com/free-psd/…',
        'magnific.com/free-video/…',
        'img.magnific.com/…',
        'assets.magnific.ai/…',
    ],
    examples: [{
        title: 'Public free Magnific image',
        description: 'A Magnific page explicitly marked as a free AI image.',
        urls: ['https://www.magnific.com/free-ai-image/vividly-colored-hummingbird-nature_186503755.htm'],
    }],
};
