const copy = {
    "en": {
        "intro": "Find your platform. Paste a link. Save what matters.",
        "search": "Search platforms…",
        "primary": "Popular platforms",
        "primaryNote": "Dedicated support for these platforms.",
        "additional": "More platforms",
        "additionalNote": "Support varies by link. Private, paid or protected content may be unavailable.",
        "more": "Show all platforms",
        "empty": "No matching platforms. Try another name.",
        "tasks": "Download pages & guides",
        "help": "Need help?",
        "free": "Free options available",
        "ads": "No ads",
        "start": "Start downloading",
        "all": "All platforms",
        "disclaimer": "Platform names and logos belong to their respective owners. FreeSaveVideo is not affiliated with them."
    },
    "zh": {
        "intro": "找到你的平台，粘贴链接，轻松保存。",
        "search": "搜索平台名称…",
        "primary": "热门平台",
        "primaryNote": "我们已提供专门支持的平台。",
        "additional": "更多支持的平台",
        "additionalNote": "可用性取决于具体链接；私密、付费或受保护的内容可能无法下载。",
        "more": "查看全部平台",
        "empty": "没有找到匹配的平台，请换个名称试试。",
        "tasks": "下载页面与指南",
        "help": "遇到问题？",
        "free": "提供免费途径",
        "ads": "无广告",
        "start": "开始下载",
        "all": "全部平台",
        "disclaimer": "平台名称和 Logo 属于各自所有者，FreeSaveVideo 与这些平台无关联。"
    },
    "de": {
        "intro": "Plattform finden. Link einfügen. Medien speichern.",
        "search": "Plattformen suchen…",
        "primary": "Beliebte Plattformen",
        "primaryNote": "Plattformen mit eigener Unterstützung.",
        "additional": "Weitere Plattformen",
        "additionalNote": "Die Verfügbarkeit hängt vom Link ab. Private, kostenpflichtige oder geschützte Inhalte können nicht verfügbar sein.",
        "more": "Alle Plattformen anzeigen",
        "empty": "Keine passenden Plattformen gefunden.",
        "tasks": "Downloadseiten & Anleitungen",
        "help": "Hilfe nötig?",
        "free": "Kostenlose Möglichkeiten",
        "ads": "Keine Werbung",
        "start": "Download starten",
        "all": "Alle Plattformen",
        "disclaimer": "Namen und Logos gehören ihren jeweiligen Eigentümern. FreeSaveVideo ist nicht mit ihnen verbunden."
    },
    "es": {
        "intro": "Encuentra tu plataforma, pega un enlace y guarda.",
        "search": "Buscar plataformas…",
        "primary": "Plataformas populares",
        "primaryNote": "Plataformas con soporte específico.",
        "additional": "Más plataformas",
        "additionalNote": "La disponibilidad depende del enlace. El contenido privado, de pago o protegido puede no estar disponible.",
        "more": "Ver todas las plataformas",
        "empty": "No se encontraron plataformas.",
        "tasks": "Páginas de descarga y guías",
        "help": "¿Necesitas ayuda?",
        "free": "Opciones gratuitas",
        "ads": "Sin anuncios",
        "start": "Empezar a descargar",
        "all": "Todas las plataformas",
        "disclaimer": "Los nombres y logotipos pertenecen a sus propietarios. FreeSaveVideo no está afiliado a estas plataformas."
    },
    "fr": {
        "intro": "Trouvez votre plateforme, collez un lien et enregistrez.",
        "search": "Rechercher une plateforme…",
        "primary": "Plateformes populaires",
        "primaryNote": "Plateformes avec une prise en charge dédiée.",
        "additional": "Autres plateformes",
        "additionalNote": "La disponibilité dépend du lien. Les contenus privés, payants ou protégés peuvent être indisponibles.",
        "more": "Voir toutes les plateformes",
        "empty": "Aucune plateforme correspondante.",
        "tasks": "Pages de téléchargement et guides",
        "help": "Besoin d’aide ?",
        "free": "Options gratuites",
        "ads": "Sans publicité",
        "start": "Télécharger",
        "all": "Toutes les plateformes",
        "disclaimer": "Les noms et logos appartiennent à leurs propriétaires. FreeSaveVideo n’est pas affilié à ces plateformes."
    },
    "id": {
        "intro": "Temukan platform, tempel tautan, lalu simpan.",
        "search": "Cari platform…",
        "primary": "Platform populer",
        "primaryNote": "Platform dengan dukungan khusus.",
        "additional": "Platform lainnya",
        "additionalNote": "Ketersediaan tergantung tautan. Konten pribadi, berbayar, atau dilindungi mungkin tidak tersedia.",
        "more": "Lihat semua platform",
        "empty": "Tidak ada platform yang cocok.",
        "tasks": "Halaman unduhan & panduan",
        "help": "Butuh bantuan?",
        "free": "Opsi gratis tersedia",
        "ads": "Tanpa iklan",
        "start": "Mulai mengunduh",
        "all": "Semua platform",
        "disclaimer": "Nama dan logo milik pemilik masing-masing. FreeSaveVideo tidak berafiliasi dengan platform tersebut."
    },
    "ja": {
        "intro": "プラットフォームを選び、リンクを貼って保存。",
        "search": "プラットフォームを検索…",
        "primary": "人気のプラットフォーム",
        "primaryNote": "専用の対応を提供しているプラットフォーム。",
        "additional": "その他のプラットフォーム",
        "additionalNote": "利用可否はリンクによって異なります。非公開、有料、保護されたコンテンツは保存できない場合があります。",
        "more": "すべてのプラットフォームを見る",
        "empty": "一致するプラットフォームがありません。",
        "tasks": "ダウンロードページとガイド",
        "help": "お困りですか？",
        "free": "無料で利用する方法",
        "ads": "広告なし",
        "start": "ダウンロードを開始",
        "all": "すべてのプラットフォーム",
        "disclaimer": "名称とロゴは各所有者に帰属します。FreeSaveVideo はこれらのプラットフォームと提携していません。"
    },
    "ko": {
        "intro": "플랫폼을 찾고 링크를 붙여넣어 저장하세요.",
        "search": "플랫폼 검색…",
        "primary": "인기 플랫폼",
        "primaryNote": "전용 지원을 제공하는 플랫폼입니다.",
        "additional": "더 많은 플랫폼",
        "additionalNote": "사용 가능 여부는 링크에 따라 다릅니다. 비공개, 유료 또는 보호된 콘텐츠는 사용할 수 없을 수 있습니다.",
        "more": "모든 플랫폼 보기",
        "empty": "일치하는 플랫폼이 없습니다.",
        "tasks": "다운로드 페이지 및 가이드",
        "help": "도움이 필요하신가요?",
        "free": "무료 이용 방법 제공",
        "ads": "광고 없음",
        "start": "다운로드 시작",
        "all": "모든 플랫폼",
        "disclaimer": "이름과 로고는 각 소유자의 자산입니다. FreeSaveVideo는 해당 플랫폼과 제휴하지 않습니다."
    },
    "ru": {
        "intro": "Найдите платформу, вставьте ссылку и сохраните.",
        "search": "Поиск платформ…",
        "primary": "Популярные платформы",
        "primaryNote": "Платформы с отдельной поддержкой.",
        "additional": "Другие платформы",
        "additionalNote": "Доступность зависит от ссылки. Закрытый, платный или защищённый контент может быть недоступен.",
        "more": "Показать все платформы",
        "empty": "Подходящих платформ не найдено.",
        "tasks": "Страницы загрузки и руководства",
        "help": "Нужна помощь?",
        "free": "Есть бесплатные способы",
        "ads": "Без рекламы",
        "start": "Начать загрузку",
        "all": "Все платформы",
        "disclaimer": "Названия и логотипы принадлежат их владельцам. FreeSaveVideo не связан с этими платформами."
    },
    "th": {
        "intro": "ค้นหาแพลตฟอร์ม วางลิงก์ แล้วบันทึก",
        "search": "ค้นหาแพลตฟอร์ม…",
        "primary": "แพลตฟอร์มยอดนิยม",
        "primaryNote": "แพลตฟอร์มที่มีการรองรับโดยเฉพาะ",
        "additional": "แพลตฟอร์มเพิ่มเติม",
        "additionalNote": "การใช้งานขึ้นอยู่กับลิงก์ เนื้อหาส่วนตัว แบบชำระเงิน หรือมีการป้องกันอาจดาวน์โหลดไม่ได้",
        "more": "ดูแพลตฟอร์มทั้งหมด",
        "empty": "ไม่พบแพลตฟอร์มที่ตรงกัน",
        "tasks": "หน้าดาวน์โหลดและคู่มือ",
        "help": "ต้องการความช่วยเหลือไหม?",
        "free": "มีวิธีใช้งานฟรี",
        "ads": "ไม่มีโฆษณา",
        "start": "เริ่มดาวน์โหลด",
        "all": "แพลตฟอร์มทั้งหมด",
        "disclaimer": "ชื่อและโลโก้เป็นของเจ้าของแต่ละราย FreeSaveVideo ไม่มีความเกี่ยวข้องกับแพลตฟอร์มเหล่านี้"
    },
    "vi": {
        "intro": "Tìm nền tảng, dán liên kết và lưu.",
        "search": "Tìm nền tảng…",
        "primary": "Nền tảng phổ biến",
        "primaryNote": "Các nền tảng có hỗ trợ riêng.",
        "additional": "Nền tảng khác",
        "additionalNote": "Khả năng sử dụng tùy thuộc vào liên kết. Nội dung riêng tư, trả phí hoặc được bảo vệ có thể không khả dụng.",
        "more": "Xem tất cả nền tảng",
        "empty": "Không tìm thấy nền tảng phù hợp.",
        "tasks": "Trang tải xuống và hướng dẫn",
        "help": "Cần trợ giúp?",
        "free": "Có cách sử dụng miễn phí",
        "ads": "Không quảng cáo",
        "start": "Bắt đầu tải xuống",
        "all": "Tất cả nền tảng",
        "disclaimer": "Tên và logo thuộc về chủ sở hữu tương ứng. FreeSaveVideo không liên kết với các nền tảng này."
    }
};

export const getPlatformDirectoryCopy = (lang: string) => copy[lang as keyof typeof copy] || copy.en;
