import type { SeoLandingPage } from './landing-pages';

export const soopliveLanding: SeoLandingPage = {
    slug: 'sooplive-video-download',
    locales: {
        en: {
            metaTitle: 'SOOP Video Downloader (AfreecaTV) - Save VOD Online | FreeSaveVideo',
            metaDescription: 'Download public SOOP videos and AfreecaTV VOD links online. Paste a vod.sooplive.com player URL, choose an available quality, and save the replay as MP4.',
            metaKeywords: ['SOOP video downloader', 'SOOP VOD download', 'AfreecaTV downloader', 'download AfreecaTV VOD', 'vod.sooplive.com download'],
            h1: 'SOOP Video Downloader (formerly AfreecaTV)',
            lede: 'Paste a public SOOP VOD or Catch link to save the available replay as MP4. Links from the former AfreecaTV domains are recognized too.',
            heroTags: ['SOOP VOD', 'AfreecaTV links', 'Catch clips', 'Available HLS quality'],
            facts: [
                'SOOP is the current name of the Korean streaming service formerly known as AfreecaTV.',
                'FreeSaveVideo reads the public VOD metadata and selects the closest available source quality; multi-part replays are shown as separate downloadable parts.',
                'Public vod.sooplive.com player links and compatible legacy AfreecaTV VOD links are supported without installing the SOOP app.',
            ],
            stepsTitle: 'How to download a SOOP video',
            steps: [
                'Open a public SOOP replay or Catch clip and copy its player URL.',
                'Paste the vod.sooplive.com link into FreeSaveVideo and start parsing.',
                'Choose your preferred video quality in the downloader settings if needed.',
                'Wait while the available HLS parts are remuxed, then save the MP4 file.',
            ],
            featuresTitle: 'Supported SOOP content and limits',
            features: [
                'Supports public SOOP VOD player and Catch URLs, including /player/VIDEO_ID/catch.',
                'Accepts compatible old vod.afreecatv.com and vod.sooplive.co.kr player links.',
                'Keeps the VOD title, broadcaster name, thumbnail, and duration when the source exposes them.',
                'Selects an available quality and lets you choose individual parts of a multi-part public replay.',
                'Private, subscriber-only, adult login-gated, deleted, live, and DRM-protected content is not supported.',
            ],
            supportedLinksTitle: 'Supported SOOP and AfreecaTV links',
            supportedLinks: [
                { title: 'SOOP VOD player', description: 'vod.sooplive.com/player/VIDEO_ID and public Catch variants.' },
                { title: 'Legacy AfreecaTV VOD', description: 'Compatible vod.afreecatv.com and vod.sooplive.co.kr player URLs are mapped to the same SOOP parser.' },
            ],
            faqTitle: 'SOOP video download FAQ',
            faqs: [
                { q: 'Is SOOP the same as AfreecaTV?', a: 'SOOP is the current brand of the Korean service previously called AfreecaTV, so people may search for either name.' },
                { q: 'Can FreeSaveVideo download SOOP Catch clips?', a: 'Yes. Paste a public /player/VIDEO_ID/catch URL and the downloader will use the available VOD stream.' },
                { q: 'Are old AfreecaTV links supported?', a: 'Compatible legacy VOD player links on AfreecaTV and the former SOOP Korean domain are recognized.' },
                { q: 'Can it download subscriber-only or private VODs?', a: 'No. FreeSaveVideo only supports media that SOOP exposes publicly without account-only access.' },
            ],
            disclaimer: 'Download only public videos you have permission to save. Respect creators, copyright, and SOOP platform rules.',
        },
        ko: {
            metaTitle: 'SOOP 동영상 다운로드 (구 아프리카TV) - VOD 저장 | FreeSaveVideo',
            metaDescription: '공개 SOOP VOD와 아프리카TV 다시보기 링크를 온라인에서 다운로드하세요. vod.sooplive.com 플레이어 주소를 붙여넣고 제공되는 화질의 영상을 MP4로 저장할 수 있습니다.',
            metaKeywords: ['SOOP 동영상 다운로드', 'SOOP VOD 다운로드', '숲 다시보기 다운로드', '아프리카TV 다운로드', '아프리카TV VOD 저장'],
            h1: 'SOOP 동영상 다운로드 (구 아프리카TV)',
            lede: '공개 SOOP 다시보기 또는 캐치 링크를 붙여넣으면 제공되는 영상을 MP4로 저장할 수 있습니다. 예전 아프리카TV VOD 주소도 인식합니다.',
            heroTags: ['SOOP VOD', '아프리카TV 링크', '캐치 영상', '화질 선택'],
            facts: [
                'SOOP은 한국 스트리밍 서비스 아프리카TV의 현재 이름입니다.',
                'FreeSaveVideo는 공개 VOD 정보를 읽어 요청한 화질과 가장 가까운 스트림을 선택하고, 여러 파트로 나뉜 다시보기는 각각 선택해 받을 수 있게 표시합니다.',
                'SOOP 앱을 설치하지 않아도 공개 vod.sooplive.com 플레이어 링크를 브라우저에서 처리할 수 있습니다.',
            ],
            stepsTitle: 'SOOP 동영상 다운로드 방법',
            steps: [
                'SOOP에서 공개 다시보기나 캐치 영상을 열고 플레이어 링크를 복사합니다.',
                '복사한 vod.sooplive.com 주소를 FreeSaveVideo 입력창에 붙여넣습니다.',
                '필요하면 다운로드 설정에서 원하는 화질을 선택한 뒤 분석을 시작합니다.',
                'HLS 영상 처리가 끝나면 완성된 MP4 파일을 저장합니다.',
            ],
            featuresTitle: '지원 범위와 제한',
            features: [
                '/player/영상번호 및 /player/영상번호/catch 형식의 공개 SOOP VOD를 지원합니다.',
                '호환되는 기존 vod.afreecatv.com 및 vod.sooplive.co.kr 주소도 지원합니다.',
                '원본에서 제공하는 제목, BJ 이름, 썸네일, 재생 시간을 파일 정보에 반영합니다.',
                '공개 다시보기의 제공 화질을 선택하며 여러 파트는 각각 선택해 다운로드할 수 있습니다.',
                '비공개, 구독자 전용, 성인 로그인 필요, 삭제됨, 라이브 및 DRM 콘텐츠는 지원하지 않습니다.',
            ],
            supportedLinksTitle: '지원하는 SOOP·아프리카TV 링크',
            supportedLinks: [
                { title: 'SOOP VOD 플레이어', description: 'vod.sooplive.com/player/영상번호 및 공개 캐치 링크를 지원합니다.' },
                { title: '기존 아프리카TV VOD', description: '호환되는 vod.afreecatv.com 및 vod.sooplive.co.kr 플레이어 링크를 같은 SOOP 분석기로 처리합니다.' },
            ],
            faqTitle: 'SOOP 다운로드 자주 묻는 질문',
            faqs: [
                { q: 'SOOP과 아프리카TV는 같은 서비스인가요?', a: 'SOOP은 아프리카TV가 변경한 현재 브랜드명입니다. 따라서 두 이름으로 모두 검색될 수 있습니다.' },
                { q: 'SOOP 캐치 영상도 다운로드할 수 있나요?', a: '네. 공개 /player/영상번호/catch 링크를 붙여넣으면 제공되는 VOD 스트림을 처리합니다.' },
                { q: '예전 아프리카TV 링크도 되나요?', a: '호환되는 기존 아프리카TV VOD 플레이어 주소와 이전 SOOP 한국 도메인을 인식합니다.' },
                { q: '구독자 전용이나 비공개 VOD도 받을 수 있나요?', a: '아니요. 로그인 권한 없이 공개적으로 접근 가능한 SOOP 영상만 지원합니다.' },
            ],
            disclaimer: '저장 권한이 있는 공개 영상만 다운로드하고 저작권, 창작자 권리 및 SOOP 이용 규칙을 준수하세요.',
        },
        ja: {
            metaTitle: 'SOOP動画ダウンローダー（旧AfreecaTV）- VOD保存 | FreeSaveVideo',
            metaDescription: '公開SOOP VODと旧AfreecaTVの動画をオンラインでダウンロード。vod.sooplive.comのプレイヤーURLを貼り付け、利用可能な画質の動画をMP4で保存できます。',
            metaKeywords: ['SOOP 動画 ダウンロード', 'SOOP VOD 保存', 'AfreecaTV ダウンロード', 'アフリカTV 動画 保存', 'vod.sooplive.com downloader'],
            h1: 'SOOP動画ダウンローダー（旧AfreecaTV）',
            lede: '公開されているSOOPのVODまたはCatchリンクを貼り付け、利用可能な動画をMP4で保存できます。旧AfreecaTVの互換VOD URLにも対応します。',
            heroTags: ['SOOP VOD', '旧AfreecaTVリンク', 'Catch動画', '画質選択'],
            facts: [
                'SOOPは、韓国の動画配信サービスAfreecaTVの現在の名称です。',
                '公開VODの情報から希望画質に近いストリームを選び、複数パートの配信は個別に選んで保存できます。',
                'SOOPアプリをインストールせず、PCやスマートフォンのブラウザから利用できます。',
            ],
            stepsTitle: 'SOOP動画をダウンロードする方法',
            steps: [
                '公開SOOP VODまたはCatch動画を開き、プレイヤーURLをコピーします。',
                'vod.sooplive.comのURLをFreeSaveVideoに貼り付けます。',
                '必要に応じて設定から希望画質を選び、解析を開始します。',
                'HLSの処理完了後、生成されたMP4を保存します。',
            ],
            featuresTitle: '対応内容と制限',
            features: [
                '/player/動画IDおよび/player/動画ID/catch形式の公開SOOP VODに対応します。',
                '互換性のある旧vod.afreecatv.comとvod.sooplive.co.krのURLも認識します。',
                '取得できる場合はタイトル、配信者名、サムネイル、再生時間を保持します。',
                '利用可能な画質を選択し、複数パートの公開VODは各パートを個別に保存できます。',
                '非公開、購読者限定、成人ログイン必須、削除済み、ライブ、DRM動画には対応しません。',
            ],
            supportedLinksTitle: '対応するSOOP・AfreecaTVリンク',
            supportedLinks: [
                { title: 'SOOP VODプレイヤー', description: 'vod.sooplive.com/player/動画IDと公開Catchリンクに対応します。' },
                { title: '旧AfreecaTV VOD', description: '互換性のある旧AfreecaTVおよびSOOP韓国ドメインのプレイヤーURLを同じ解析機能で処理します。' },
            ],
            faqTitle: 'SOOP動画保存のよくある質問',
            faqs: [
                { q: 'SOOPとAfreecaTVは同じサービスですか？', a: 'SOOPは、以前AfreecaTVと呼ばれていた韓国サービスの現在のブランド名です。' },
                { q: 'SOOPのCatch動画も保存できますか？', a: 'はい。公開/player/動画ID/catch URLから利用可能なVODストリームを処理します。' },
                { q: '古いAfreecaTV URLも使えますか？', a: '互換性のある旧AfreecaTV VODプレイヤーURLと旧SOOP韓国ドメインを認識します。' },
                { q: '限定公開や会員限定VODも保存できますか？', a: 'いいえ。アカウント限定ではなく、一般公開されている動画だけが対象です。' },
            ],
            disclaimer: '保存する権利がある公開動画だけを対象とし、著作権、配信者の権利、SOOPの利用規約を守ってください。',
        },
        th: {
            metaTitle: 'ดาวน์โหลดวิดีโอ SOOP (เดิม AfreecaTV) - บันทึก VOD | FreeSaveVideo',
            metaDescription: 'ดาวน์โหลด VOD สาธารณะจาก SOOP และลิงก์ AfreecaTV เดิม วาง URL จาก vod.sooplive.com เลือกคุณภาพที่มี แล้วบันทึกวิดีโอเป็น MP4 ออนไลน์',
            metaKeywords: ['ดาวน์โหลดวิดีโอ SOOP', 'ดาวน์โหลด SOOP VOD', 'AfreecaTV downloader', 'ดาวน์โหลด AfreecaTV', 'บันทึกวิดีโอ SOOP'],
            h1: 'ดาวน์โหลดวิดีโอ SOOP (เดิม AfreecaTV)',
            lede: 'วางลิงก์ VOD หรือ Catch แบบสาธารณะจาก SOOP เพื่อบันทึกวิดีโอที่มีเป็น MP4 และยังรองรับลิงก์ VOD เดิมของ AfreecaTV ที่เข้ากันได้',
            heroTags: ['SOOP VOD', 'ลิงก์ AfreecaTV', 'คลิป Catch', 'เลือกคุณภาพ'],
            facts: [
                'SOOP คือชื่อปัจจุบันของบริการสตรีมมิงเกาหลีที่เดิมชื่อ AfreecaTV',
                'FreeSaveVideo อ่านข้อมูล VOD สาธารณะ เลือกสตรีมที่ใกล้กับคุณภาพที่ต้องการ และแสดงวิดีโอหลายพาร์ตให้เลือกดาวน์โหลดแยกกัน',
                'ใช้งานลิงก์ vod.sooplive.com ผ่านเบราว์เซอร์ได้โดยไม่ต้องติดตั้งแอป SOOP',
            ],
            stepsTitle: 'วิธีดาวน์โหลดวิดีโอ SOOP',
            steps: [
                'เปิดวิดีโอย้อนหลังหรือคลิป Catch แบบสาธารณะบน SOOP แล้วคัดลอก URL ของหน้าเล่น',
                'วางลิงก์ vod.sooplive.com ลงใน FreeSaveVideo',
                'เลือกคุณภาพวิดีโอที่ต้องการในการตั้งค่า แล้วเริ่มวิเคราะห์ลิงก์',
                'รอให้ระบบประมวลผล HLS จากนั้นบันทึกไฟล์ MP4',
            ],
            featuresTitle: 'เนื้อหาที่รองรับและข้อจำกัด',
            features: [
                'รองรับ SOOP VOD สาธารณะรูปแบบ /player/VIDEO_ID และ /player/VIDEO_ID/catch',
                'รองรับลิงก์เดิมที่เข้ากันได้จาก vod.afreecatv.com และ vod.sooplive.co.kr',
                'เก็บชื่อวิดีโอ ชื่อสตรีมเมอร์ ภาพปก และระยะเวลาเมื่อแหล่งข้อมูลมีให้',
                'เลือกคุณภาพที่มีและให้เลือกดาวน์โหลดแต่ละพาร์ตของ VOD สาธารณะได้',
                'ไม่รองรับวิดีโอส่วนตัว สำหรับสมาชิก ต้องล็อกอินยืนยันอายุ ถูกลบ ไลฟ์สด หรือมี DRM',
            ],
            supportedLinksTitle: 'ลิงก์ SOOP และ AfreecaTV ที่รองรับ',
            supportedLinks: [
                { title: 'หน้าเล่น SOOP VOD', description: 'รองรับ vod.sooplive.com/player/VIDEO_ID และลิงก์ Catch สาธารณะ' },
                { title: 'AfreecaTV VOD เดิม', description: 'ลิงก์หน้าเล่นจาก AfreecaTV และโดเมน SOOP เก่าที่เข้ากันได้จะใช้ตัวแยก SOOP เดียวกัน' },
            ],
            faqTitle: 'คำถามที่พบบ่อยเกี่ยวกับการดาวน์โหลด SOOP',
            faqs: [
                { q: 'SOOP กับ AfreecaTV คือบริการเดียวกันหรือไม่?', a: 'SOOP คือชื่อแบรนด์ปัจจุบันของบริการเกาหลีที่เดิมชื่อ AfreecaTV ผู้ใช้จึงอาจค้นหาด้วยทั้งสองชื่อ' },
                { q: 'ดาวน์โหลดคลิป SOOP Catch ได้หรือไม่?', a: 'ได้ วางลิงก์ /player/VIDEO_ID/catch แบบสาธารณะเพื่อประมวลผลสตรีม VOD ที่มี' },
                { q: 'ใช้ลิงก์ AfreecaTV เก่าได้หรือไม่?', a: 'รองรับ URL หน้าเล่น VOD เดิมของ AfreecaTV และโดเมน SOOP เก่าที่เข้ากันได้' },
                { q: 'ดาวน์โหลด VOD ส่วนตัวหรือสำหรับสมาชิกได้หรือไม่?', a: 'ไม่ได้ รองรับเฉพาะวิดีโอ SOOP ที่เข้าถึงได้แบบสาธารณะโดยไม่ต้องใช้สิทธิ์บัญชี' },
            ],
            disclaimer: 'ดาวน์โหลดเฉพาะวิดีโอสาธารณะที่คุณมีสิทธิ์บันทึก และเคารพลิขสิทธิ์ สิทธิ์ของผู้สร้าง และกฎของ SOOP',
        },
    },
    supportedLinkFormats: [
        'vod.sooplive.com/player/VIDEO_ID',
        'vod.sooplive.com/player/VIDEO_ID/catch',
        'vod.afreecatv.com/PLAYER/STATION/VIDEO_ID',
    ],
    examples: [{
        title: 'SOOP Catch VOD',
        description: 'A public Catch player URL resolved through the SOOP VOD API.',
        urls: ['https://vod.sooplive.com/player/201688145/catch'],
    }],
};
