{{- if .Values.socialSync.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-metrics
  namespace: infra
  labels:
    {{- include "cobalt-chart.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.socialSync.schedule | quote }}
  concurrencyPolicy: {{ .Values.socialSync.concurrencyPolicy | default "Forbid" | quote }}
  successfulJobsHistoryLimit: {{ .Values.socialSync.successfulJobsHistoryLimit | default 1 }}
  failedJobsHistoryLimit: {{ .Values.socialSync.failedJobsHistoryLimit | default 3 }}
  startingDeadlineSeconds: {{ .Values.socialSync.startingDeadlineSeconds | default 600 }}
  suspend: {{ .Values.socialSync.suspend | default false }}
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            {{- include "cobalt-chart.selectorLabels" . | nindent 12 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          containers:
            - name: social-sync
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["node", "src/util/sync-enabled-accounts.js"]
              args:
                - "--concurrency={{ .Values.socialSync.concurrency | default 2 }}"
                - "--recent={{ .Values.socialSync.recentLimit | default 5 }}"
                - "--pinned={{ .Values.socialSync.pinnedLimit | default 3 }}"
                - "--thumbnailLimit={{ .Values.socialSync.thumbnailLimit | default 0 }}"
                - "--tiktokIntervalMinutes={{ .Values.socialSync.tiktokIntervalMinutes | default 240 }}"
                - "--instagramIntervalMinutes={{ .Values.socialSync.instagramIntervalMinutes | default 720 }}"
                - "--otherIntervalMinutes={{ .Values.socialSync.otherIntervalMinutes | default 720 }}"
                - "--intervalSlackMinutes={{ .Values.socialSync.intervalSlackMinutes | default 5 }}"
              env:
                # Database Configuration
                - name: DB_TYPE
                  value: {{ .Values.database.type | quote }}
                - name: DB_HOST
                  value: {{ .Values.database.host | quote }}
                - name: DB_PORT
                  value: {{ .Values.database.port | quote }}
                - name: DB_USER
                  value: {{ .Values.database.user | quote }}
                - name: DB_PASSWORD
                  value: {{ .Values.database.password | quote }}
                - name: DB_NAME
                  value: {{ .Values.database.name | quote }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
