version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@3.0.0

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          name: check-api-changes
          base-revision: << pipeline.git.branch >>
          config-path: .circleci/deploy.yml
          mapping: |
            api/.* run-api-deploy true
