{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cobalt-postgresql.secretName" . }}
  labels:
    {{- include "cobalt-postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.userPasswordKey }}: {{ required "auth.password is required when auth.existingSecret is empty" .Values.auth.password | quote }}
  {{ .Values.auth.postgresPasswordKey }}: {{ required "auth.postgresPassword is required when auth.existingSecret is empty" .Values.auth.postgresPassword | quote }}
{{- end }}
