const en = {
    eyebrow: 'YOUR YOUTUBE DOWNLOAD SPACE',
    intro: 'Find a video. Make it yours to keep.',
    description: 'Search by title, artist or topic, or paste a YouTube link. Choose a video and save it in the format you need.',
    input: 'YouTube link or search keywords', placeholder: 'Paste a YouTube link or search for a video',
    search: 'Search videos', open: 'Open video', searching: 'Finding videos...', paste: 'Paste', clear: 'Clear',
    try: 'Try a search', results: 'Search results', choose: 'Choose a video to download', select: 'Choose video', selected: 'Selected',
    empty: 'No videos found', emptyBody: 'Try a song title, creator name or a more specific topic.',
    invalid: 'Enter 2-120 search characters or a valid YouTube video or playlist link.',
    error: 'Search is unavailable right now. Please try again.', busy: 'Too many searches. Please wait a moment and try again.',
    timeout: 'The search took too long. Please try again.', clipboard: 'Paste with Ctrl+V or your device\'s paste menu.',
    ready: 'Ready when you are', readyBody: 'Search for a video above, or paste a link you already have.',
    video: 'Video + audio', audio: 'Audio only', mute: 'Video only', quality: 'Video quality', best: 'Best available',
    format: 'Audio format', bitrate: 'Audio bitrate', download: 'Download', downloading: 'Preparing download...',
    started: 'Download handed off. Follow its progress in the download queue or your browser.',
    sourceNote: 'Available quality depends on the source. Your download may use a lower quality if needed.',
    searchNote: 'Searching does not use download points. Downloads follow your account plan and points rules.',
    watch: 'Watch on YouTube', change: 'Choose another video', playlist: 'Playlist videos', batch: 'Download playlist',
    step1: 'Find', step1Body: 'Search a title or paste a YouTube link.',
    step2: 'Choose', step2Body: 'Pick a video, quality and audio format.',
    step3: 'Save', step3Body: 'Start the download and keep track of progress.',
    related: 'More YouTube tools', guide: 'YouTube download guide', shorts: 'YouTube Shorts', tools: 'All download tools',
};

type Copy = typeof en;
const copies: Record<string, Copy> = {
    en,
    id: {
        eyebrow: 'RUANG UNDUHAN YOUTUBE ANDA', intro: 'Temukan video dan simpan konten favorit.', description: 'Cari berdasarkan judul, artis, atau topik, atau tempel tautan YouTube. Pilih video dan simpan dalam format yang diinginkan.',
        input: 'Tautan YouTube atau kata kunci', placeholder: 'Tempel tautan YouTube atau cari video', search: 'Cari video', open: 'Buka video', searching: 'Mencari video...', paste: 'Tempel', clear: 'Hapus', try: 'Coba pencarian', results: 'Hasil pencarian', choose: 'Pilih video untuk diunduh', select: 'Pilih video', selected: 'Dipilih', empty: 'Video tidak ditemukan', emptyBody: 'Coba judul lagu, nama kreator, atau topik yang lebih spesifik.',
        invalid: 'Masukkan 2–120 karakter atau tautan video atau playlist YouTube yang valid.', error: 'Pencarian sedang tidak tersedia. Coba lagi.', busy: 'Terlalu banyak pencarian. Tunggu sebentar.', timeout: 'Pencarian terlalu lama. Coba lagi.', clipboard: 'Gunakan Ctrl+V atau menu tempel perangkat.', ready: 'Mulai dengan pencarian', readyBody: 'Cari video di atas atau tempel tautan.',
        video: 'Video dengan audio', audio: 'Audio saja', mute: 'Video tanpa audio', quality: 'Kualitas video', best: 'Terbaik yang tersedia', format: 'Format audio', bitrate: 'Bitrate audio', download: 'Unduh', downloading: 'Menyiapkan unduhan...', started: 'Unduhan diteruskan. Pantau kemajuan di antrean atau browser.', sourceNote: 'Kualitas bergantung pada video asli. Kualitas lebih rendah digunakan jika diperlukan.', searchNote: 'Pencarian tidak menggunakan poin. Unduhan mengikuti paket akun dan aturan poin.', watch: 'Tonton di YouTube', change: 'Pilih video lain', playlist: 'Video playlist', batch: 'Unduh playlist',
        step1: 'Temukan', step1Body: 'Cari judul atau tempel tautan YouTube.', step2: 'Pilih', step2Body: 'Pilih video, kualitas, dan format audio.', step3: 'Simpan', step3Body: 'Mulai unduhan dan pantau kemajuannya.', related: 'Alat YouTube lainnya', guide: 'Panduan unduhan YouTube', shorts: 'YouTube Shorts', tools: 'Semua alat unduhan',
    },
    de: {
        eyebrow: 'DEIN YOUTUBE-DOWNLOADBEREICH', intro: 'Video finden und Lieblingsinhalte speichern.', description: 'Suche nach Titel, Künstler oder Thema oder füge einen YouTube-Link ein. Wähle ein Video und das gewünschte Format.',
        input: 'YouTube-Link oder Suchbegriffe', placeholder: 'YouTube-Link einfügen oder Video suchen', search: 'Videos suchen', open: 'Video öffnen', searching: 'Videos werden gesucht...', paste: 'Einfügen', clear: 'Leeren',
        try: 'Suche ausprobieren', results: 'Suchergebnisse', choose: 'Video zum Herunterladen auswählen', select: 'Video auswählen', selected: 'Ausgewählt', empty: 'Keine Videos gefunden', emptyBody: 'Versuche einen Songtitel, Kanalnamen oder ein genaueres Thema.',
        invalid: 'Gib 2–120 Zeichen oder einen gültigen YouTube-Video- oder Playlist-Link ein.', error: 'Die Suche ist derzeit nicht verfügbar. Bitte erneut versuchen.', busy: 'Zu viele Suchanfragen. Bitte kurz warten.', timeout: 'Die Suche dauerte zu lange. Bitte erneut versuchen.', clipboard: 'Nutze Strg+V oder das Einfügen-Menü deines Geräts.',
        ready: 'Beginne mit einer Suche', readyBody: 'Suche oben nach einem Video oder füge einen Link ein.', video: 'Video mit Ton', audio: 'Nur Audio', mute: 'Video ohne Ton', quality: 'Videoqualität', best: 'Beste verfügbare Qualität', format: 'Audioformat', bitrate: 'Audio-Bitrate', download: 'Herunterladen', downloading: 'Download wird vorbereitet...', started: 'Download übergeben. Verfolge den Fortschritt in der Warteschlange oder im Browser.',
        sourceNote: 'Die Qualität hängt vom Originalvideo ab. Falls nötig wird eine niedrigere Qualität verwendet.', searchNote: 'Die Suche verbraucht keine Downloadpunkte. Für Downloads gelten dein Tarif und die Punkteregeln.', watch: 'Auf YouTube ansehen', change: 'Anderes Video auswählen', playlist: 'Playlist-Videos', batch: 'Playlist herunterladen',
        step1: 'Finden', step1Body: 'Titel suchen oder YouTube-Link einfügen.', step2: 'Auswählen', step2Body: 'Video, Qualität und Audioformat auswählen.', step3: 'Speichern', step3Body: 'Download starten und Fortschritt verfolgen.', related: 'Weitere YouTube-Werkzeuge', guide: 'YouTube-Download-Anleitung', shorts: 'YouTube Shorts', tools: 'Alle Download-Werkzeuge',
    },
    es: {
        eyebrow: 'TU ESPACIO DE DESCARGAS DE YOUTUBE', intro: 'Encuentra un vídeo y guarda lo que te gusta.', description: 'Busca por título, artista o tema, o pega un enlace de YouTube. Elige un vídeo y el formato que necesitas.',
        input: 'Enlace de YouTube o palabras de búsqueda', placeholder: 'Pega un enlace de YouTube o busca un vídeo', search: 'Buscar vídeos', open: 'Abrir vídeo', searching: 'Buscando vídeos...', paste: 'Pegar', clear: 'Borrar', try: 'Prueba una búsqueda', results: 'Resultados', choose: 'Elige un vídeo para descargar', select: 'Elegir vídeo', selected: 'Seleccionado', empty: 'No se encontraron vídeos', emptyBody: 'Prueba el título de una canción, un creador o un tema más específico.',
        invalid: 'Introduce entre 2 y 120 caracteres o un enlace válido de vídeo o lista de YouTube.', error: 'La búsqueda no está disponible. Inténtalo de nuevo.', busy: 'Demasiadas búsquedas. Espera un momento.', timeout: 'La búsqueda tardó demasiado. Inténtalo de nuevo.', clipboard: 'Usa Ctrl+V o el menú de pegar de tu dispositivo.', ready: 'Empieza con una búsqueda', readyBody: 'Busca un vídeo arriba o pega un enlace.',
        video: 'Vídeo con audio', audio: 'Solo audio', mute: 'Vídeo sin audio', quality: 'Calidad de vídeo', best: 'Mejor disponible', format: 'Formato de audio', bitrate: 'Tasa de bits de audio', download: 'Descargar', downloading: 'Preparando descarga...', started: 'Descarga enviada. Sigue el progreso en la cola o en tu navegador.', sourceNote: 'La calidad depende del vídeo original. Se usará una menor si es necesario.', searchNote: 'Buscar no consume puntos. Las descargas siguen las reglas de tu plan y tus puntos.', watch: 'Ver en YouTube', change: 'Elegir otro vídeo', playlist: 'Vídeos de la lista', batch: 'Descargar lista',
        step1: 'Buscar', step1Body: 'Busca un título o pega un enlace de YouTube.', step2: 'Elegir', step2Body: 'Elige el vídeo, la calidad y el formato de audio.', step3: 'Guardar', step3Body: 'Inicia la descarga y sigue el progreso.', related: 'Más herramientas de YouTube', guide: 'Guía de descarga de YouTube', shorts: 'YouTube Shorts', tools: 'Todas las herramientas de descarga',
    },
    fr: {
        eyebrow: 'VOTRE ESPACE DE TÉLÉCHARGEMENT YOUTUBE', intro: 'Trouvez une vidéo et gardez vos favoris.', description: 'Recherchez un titre, un artiste ou un sujet, ou collez un lien YouTube. Choisissez une vidéo et le format souhaité.',
        input: 'Lien YouTube ou mots-clés', placeholder: 'Collez un lien YouTube ou recherchez une vidéo', search: 'Rechercher des vidéos', open: 'Ouvrir la vidéo', searching: 'Recherche en cours...', paste: 'Coller', clear: 'Effacer', try: 'Essayez une recherche', results: 'Résultats de recherche', choose: 'Choisissez une vidéo à télécharger', select: 'Choisir la vidéo', selected: 'Sélectionnée', empty: 'Aucune vidéo trouvée', emptyBody: 'Essayez un titre de chanson, un créateur ou un sujet plus précis.',
        invalid: 'Saisissez 2 à 120 caractères ou un lien YouTube de vidéo ou de playlist valide.', error: 'La recherche est indisponible. Réessayez.', busy: 'Trop de recherches. Patientez un instant.', timeout: 'La recherche a pris trop de temps. Réessayez.', clipboard: 'Utilisez Ctrl+V ou le menu de collage de votre appareil.', ready: 'Commencez par une recherche', readyBody: 'Recherchez une vidéo ci-dessus ou collez un lien.',
        video: 'Vidéo avec audio', audio: 'Audio uniquement', mute: 'Vidéo sans audio', quality: 'Qualité vidéo', best: 'Meilleure disponible', format: 'Format audio', bitrate: 'Débit audio', download: 'Télécharger', downloading: 'Préparation du téléchargement...', started: 'Téléchargement transmis. Suivez sa progression dans la file ou le navigateur.', sourceNote: 'La qualité dépend de la vidéo source. Une qualité inférieure sera utilisée si nécessaire.', searchNote: 'La recherche ne consomme pas de points. Les téléchargements suivent les règles de votre offre et de vos points.', watch: 'Voir sur YouTube', change: 'Choisir une autre vidéo', playlist: 'Vidéos de la playlist', batch: 'Télécharger la playlist',
        step1: 'Trouver', step1Body: 'Recherchez un titre ou collez un lien YouTube.', step2: 'Choisir', step2Body: 'Choisissez la vidéo, la qualité et le format audio.', step3: 'Enregistrer', step3Body: 'Lancez le téléchargement et suivez sa progression.', related: 'Autres outils YouTube', guide: 'Guide de téléchargement YouTube', shorts: 'YouTube Shorts', tools: 'Tous les outils de téléchargement',
    },
    ja: {
        eyebrow: 'YOUTUBE ダウンロード専用スペース', intro: '動画を探して、お気に入りを保存。', description: 'タイトル、アーティスト、テーマで検索するか、YouTube のリンクを貼り付けてください。動画を選び、必要な形式で保存できます。',
        input: 'YouTube リンクまたは検索キーワード', placeholder: 'YouTube リンクを貼り付けるか、動画を検索', search: '動画を検索', open: '動画を開く', searching: '検索中...', paste: '貼り付け', clear: 'クリア', try: '検索してみる', results: '検索結果', choose: 'ダウンロードする動画を選択', select: '動画を選択', selected: '選択済み', empty: '動画が見つかりません', emptyBody: '曲名、投稿者名、より具体的なテーマで検索してください。',
        invalid: '2～120 文字のキーワード、または有効な YouTube 動画・再生リストのリンクを入力してください。', error: '検索を利用できません。もう一度お試しください。', busy: '検索が多すぎます。少し待ってからお試しください。', timeout: '検索がタイムアウトしました。再試行してください。', clipboard: 'Ctrl+V または端末の貼り付けメニューを使ってください。', ready: '検索から始めましょう', readyBody: '上の欄で動画を検索するか、リンクを貼り付けてください。',
        video: '映像と音声', audio: '音声のみ', mute: '映像のみ', quality: '画質', best: '利用可能な最高画質', format: '音声形式', bitrate: '音声ビットレート', download: 'ダウンロード', downloading: 'ダウンロードを準備中...', started: 'ダウンロードを開始しました。キューまたはブラウザで進行状況を確認してください。', sourceNote: '画質は元の動画によって異なります。必要に応じて低い画質が使われます。', searchNote: '検索ではポイントを消費しません。ダウンロードにはアカウントのプランとポイント規則が適用されます。', watch: 'YouTube で見る', change: '別の動画を選択', playlist: '再生リストの動画', batch: '再生リストをダウンロード',
        step1: '探す', step1Body: 'タイトルで検索するかリンクを貼り付けます。', step2: '選ぶ', step2Body: '動画、画質、音声形式を選びます。', step3: '保存', step3Body: 'ダウンロードを開始し、進行状況を確認します。', related: 'その他の YouTube ツール', guide: 'YouTube ダウンロードガイド', shorts: 'YouTube Shorts', tools: 'すべてのダウンロードツール',
    },
    ko: {
        eyebrow: 'YOUTUBE 전용 다운로드 공간', intro: '동영상을 찾아 원하는 콘텐츠를 저장하세요.', description: '제목, 아티스트, 주제로 검색하거나 YouTube 링크를 붙여넣으세요. 동영상을 선택하고 원하는 형식으로 저장하세요.',
        input: 'YouTube 링크 또는 검색어', placeholder: 'YouTube 링크를 붙여넣거나 동영상 검색', search: '동영상 검색', open: '동영상 열기', searching: '검색 중...', paste: '붙여넣기', clear: '지우기', try: '검색해 보세요', results: '검색 결과', choose: '다운로드할 동영상 선택', select: '동영상 선택', selected: '선택됨', empty: '동영상을 찾을 수 없습니다', emptyBody: '노래 제목, 크리에이터 이름 또는 구체적인 주제로 검색하세요.',
        invalid: '2~120자의 검색어 또는 올바른 YouTube 동영상이나 재생목록 링크를 입력하세요.', error: '지금은 검색할 수 없습니다. 다시 시도하세요.', busy: '검색 요청이 너무 많습니다. 잠시 후 다시 시도하세요.', timeout: '검색 시간이 초과되었습니다. 다시 시도하세요.', clipboard: 'Ctrl+V 또는 기기의 붙여넣기 메뉴를 사용하세요.', ready: '검색부터 시작하세요', readyBody: '위에서 동영상을 검색하거나 링크를 붙여넣으세요.',
        video: '영상과 소리', audio: '오디오만', mute: '영상만', quality: '화질', best: '최고 화질', format: '오디오 형식', bitrate: '오디오 비트레이트', download: '다운로드', downloading: '다운로드 준비 중...', started: '다운로드를 전달했습니다. 대기열이나 브라우저에서 진행 상황을 확인하세요.', sourceNote: '화질은 원본에 따라 달라집니다. 필요한 경우 낮은 화질을 사용합니다.', searchNote: '검색은 포인트를 사용하지 않습니다. 다운로드에는 계정 요금제와 포인트 규칙이 적용됩니다.', watch: 'YouTube에서 보기', change: '다른 동영상 선택', playlist: '재생목록 동영상', batch: '재생목록 다운로드',
        step1: '찾기', step1Body: '제목을 검색하거나 YouTube 링크를 붙여넣으세요.', step2: '선택', step2Body: '동영상, 화질, 오디오 형식을 선택하세요.', step3: '저장', step3Body: '다운로드를 시작하고 진행 상황을 확인하세요.', related: '더 많은 YouTube 도구', guide: 'YouTube 다운로드 가이드', shorts: 'YouTube Shorts', tools: '모든 다운로드 도구',
    },
    ru: {
        eyebrow: 'ВАШ РАЗДЕЛ ЗАГРУЗКИ YOUTUBE', intro: 'Найдите видео и сохраните любимое.', description: 'Ищите по названию, исполнителю или теме либо вставьте ссылку YouTube. Выберите видео и нужный формат.',
        input: 'Ссылка YouTube или поисковый запрос', placeholder: 'Вставьте ссылку YouTube или найдите видео', search: 'Найти видео', open: 'Открыть видео', searching: 'Поиск видео...', paste: 'Вставить', clear: 'Очистить', try: 'Попробуйте поиск', results: 'Результаты поиска', choose: 'Выберите видео для скачивания', select: 'Выбрать видео', selected: 'Выбрано', empty: 'Видео не найдены', emptyBody: 'Попробуйте название песни, имя автора или более точную тему.',
        invalid: 'Введите от 2 до 120 символов или действительную ссылку на видео или плейлист YouTube.', error: 'Поиск сейчас недоступен. Повторите попытку.', busy: 'Слишком много запросов. Подождите немного.', timeout: 'Поиск занял слишком много времени. Повторите попытку.', clipboard: 'Используйте Ctrl+V или меню вставки устройства.', ready: 'Начните с поиска', readyBody: 'Найдите видео выше или вставьте ссылку.',
        video: 'Видео со звуком', audio: 'Только аудио', mute: 'Видео без звука', quality: 'Качество видео', best: 'Лучшее доступное', format: 'Формат аудио', bitrate: 'Битрейт аудио', download: 'Скачать', downloading: 'Подготовка загрузки...', started: 'Загрузка передана. Следите за ней в очереди или браузере.', sourceNote: 'Качество зависит от исходного видео. При необходимости используется более низкое.', searchNote: 'Поиск не расходует баллы. Для скачивания действуют правила вашего тарифа и баллов.', watch: 'Смотреть на YouTube', change: 'Выбрать другое видео', playlist: 'Видео плейлиста', batch: 'Скачать плейлист',
        step1: 'Найти', step1Body: 'Найдите по названию или вставьте ссылку YouTube.', step2: 'Выбрать', step2Body: 'Выберите видео, качество и формат аудио.', step3: 'Сохранить', step3Body: 'Начните скачивание и следите за ходом загрузки.', related: 'Другие инструменты YouTube', guide: 'Руководство по скачиванию YouTube', shorts: 'YouTube Shorts', tools: 'Все инструменты скачивания',
    },
    th: {
        eyebrow: 'พื้นที่ดาวน์โหลด YOUTUBE ของคุณ', intro: 'ค้นหาวิดีโอแล้วบันทึกสิ่งที่ชอบ', description: 'ค้นหาด้วยชื่อ ศิลปิน หรือหัวข้อ หรือวางลิงก์ YouTube เลือกวิดีโอและบันทึกในรูปแบบที่ต้องการ',
        input: 'ลิงก์ YouTube หรือคำค้นหา', placeholder: 'วางลิงก์ YouTube หรือค้นหาวิดีโอ', search: 'ค้นหาวิดีโอ', open: 'เปิดวิดีโอ', searching: 'กำลังค้นหา...', paste: 'วาง', clear: 'ล้าง', try: 'ลองค้นหา', results: 'ผลการค้นหา', choose: 'เลือกวิดีโอที่จะดาวน์โหลด', select: 'เลือกวิดีโอ', selected: 'เลือกแล้ว', empty: 'ไม่พบวิดีโอ', emptyBody: 'ลองชื่อเพลง ชื่อผู้สร้าง หรือหัวข้อที่เฉพาะเจาะจงขึ้น',
        invalid: 'ป้อนคำค้นหา 2–120 ตัวอักษร หรือลิงก์วิดีโอหรือเพลย์ลิสต์ YouTube ที่ถูกต้อง', error: 'ค้นหาไม่ได้ในขณะนี้ โปรดลองอีกครั้ง', busy: 'มีคำขอค้นหามากเกินไป โปรดรอสักครู่', timeout: 'การค้นหาหมดเวลา โปรดลองอีกครั้ง', clipboard: 'ใช้ Ctrl+V หรือเมนูวางของอุปกรณ์', ready: 'เริ่มต้นด้วยการค้นหา', readyBody: 'ค้นหาวิดีโอด้านบนหรือวางลิงก์',
        video: 'วิดีโอพร้อมเสียง', audio: 'เสียงเท่านั้น', mute: 'วิดีโอเท่านั้น', quality: 'คุณภาพวิดีโอ', best: 'ดีที่สุดที่มี', format: 'รูปแบบเสียง', bitrate: 'บิตเรตเสียง', download: 'ดาวน์โหลด', downloading: 'กำลังเตรียมดาวน์โหลด...', started: 'ส่งต่อการดาวน์โหลดแล้ว ดูความคืบหน้าในคิวหรือเบราว์เซอร์', sourceNote: 'คุณภาพขึ้นอยู่กับวิดีโอต้นฉบับ อาจใช้คุณภาพต่ำลงเมื่อจำเป็น', searchNote: 'การค้นหาไม่ใช้คะแนน การดาวน์โหลดเป็นไปตามแพ็กเกจและกฎคะแนนของบัญชี', watch: 'ดูบน YouTube', change: 'เลือกวิดีโออื่น', playlist: 'วิดีโอในเพลย์ลิสต์', batch: 'ดาวน์โหลดเพลย์ลิสต์',
        step1: 'ค้นหา', step1Body: 'ค้นหาชื่อหรือวางลิงก์ YouTube', step2: 'เลือก', step2Body: 'เลือกวิดีโอ คุณภาพ และรูปแบบเสียง', step3: 'บันทึก', step3Body: 'เริ่มดาวน์โหลดและติดตามความคืบหน้า', related: 'เครื่องมือ YouTube เพิ่มเติม', guide: 'คู่มือดาวน์โหลด YouTube', shorts: 'YouTube Shorts', tools: 'เครื่องมือดาวน์โหลดทั้งหมด',
    },
    vi: {
        eyebrow: 'KHÔNG GIAN TẢI YOUTUBE CỦA BẠN', intro: 'Tìm video và lưu nội dung yêu thích.', description: 'Tìm theo tiêu đề, nghệ sĩ hoặc chủ đề, hoặc dán liên kết YouTube. Chọn video và lưu theo định dạng bạn cần.',
        input: 'Liên kết YouTube hoặc từ khóa', placeholder: 'Dán liên kết YouTube hoặc tìm video', search: 'Tìm video', open: 'Mở video', searching: 'Đang tìm video...', paste: 'Dán', clear: 'Xóa', try: 'Thử tìm kiếm', results: 'Kết quả tìm kiếm', choose: 'Chọn video để tải', select: 'Chọn video', selected: 'Đã chọn', empty: 'Không tìm thấy video', emptyBody: 'Thử tên bài hát, tên người sáng tạo hoặc chủ đề cụ thể hơn.',
        invalid: 'Nhập 2–120 ký tự hoặc liên kết video hay danh sách phát YouTube hợp lệ.', error: 'Hiện không thể tìm kiếm. Vui lòng thử lại.', busy: 'Quá nhiều lượt tìm kiếm. Vui lòng đợi một chút.', timeout: 'Tìm kiếm hết thời gian. Vui lòng thử lại.', clipboard: 'Dùng Ctrl+V hoặc menu dán của thiết bị.', ready: 'Bắt đầu bằng một tìm kiếm', readyBody: 'Tìm video ở trên hoặc dán liên kết.',
        video: 'Video có âm thanh', audio: 'Chỉ âm thanh', mute: 'Video không âm thanh', quality: 'Chất lượng video', best: 'Tốt nhất hiện có', format: 'Định dạng âm thanh', bitrate: 'Tốc độ bit âm thanh', download: 'Tải xuống', downloading: 'Đang chuẩn bị tải...', started: 'Đã chuyển yêu cầu tải. Theo dõi trong hàng đợi hoặc trình duyệt.', sourceNote: 'Chất lượng phụ thuộc vào video gốc. Có thể dùng chất lượng thấp hơn khi cần.', searchNote: 'Tìm kiếm không dùng điểm. Tải xuống tuân theo gói tài khoản và quy tắc điểm.', watch: 'Xem trên YouTube', change: 'Chọn video khác', playlist: 'Video trong danh sách phát', batch: 'Tải danh sách phát',
        step1: 'Tìm', step1Body: 'Tìm tiêu đề hoặc dán liên kết YouTube.', step2: 'Chọn', step2Body: 'Chọn video, chất lượng và định dạng âm thanh.', step3: 'Lưu', step3Body: 'Bắt đầu tải và theo dõi tiến trình.', related: 'Các công cụ YouTube khác', guide: 'Hướng dẫn tải YouTube', shorts: 'YouTube Shorts', tools: 'Tất cả công cụ tải xuống',
    },
    zh: {
        eyebrow: '\u4f60\u7684 YOUTUBE \u4e0b\u8f7d\u7a7a\u95f4', intro: '\u627e\u5230\u89c6\u9891\uff0c\u4fdd\u5b58\u559c\u6b22\u7684\u5185\u5bb9\u3002',
        description: '\u641c\u7d22\u6807\u9898\u3001\u6b4c\u624b\u6216\u4e3b\u9898\uff0c\u4e5f\u53ef\u4ee5\u7c98\u8d34 YouTube \u94fe\u63a5\u3002\u9009\u62e9\u89c6\u9891\uff0c\u4ee5\u9700\u8981\u7684\u683c\u5f0f\u4fdd\u5b58\u3002',
        input: 'YouTube \u94fe\u63a5\u6216\u641c\u7d22\u5173\u952e\u8bcd', placeholder: '\u7c98\u8d34 YouTube \u94fe\u63a5\uff0c\u6216\u8f93\u5165\u5173\u952e\u8bcd\u641c\u7d22\u89c6\u9891',
        search: '\u641c\u7d22\u89c6\u9891', open: '\u6253\u5f00\u89c6\u9891', searching: '\u6b63\u5728\u641c\u7d22...', paste: '\u7c98\u8d34', clear: '\u6e05\u7a7a',
        try: '\u8bd5\u8bd5\u641c\u7d22', results: '\u641c\u7d22\u7ed3\u679c', choose: '\u9009\u62e9\u8981\u4e0b\u8f7d\u7684\u89c6\u9891', select: '\u9009\u62e9\u89c6\u9891', selected: '\u5df2\u9009\u62e9',
        empty: '\u6ca1\u6709\u627e\u5230\u89c6\u9891', emptyBody: '\u8bd5\u8bd5\u6b4c\u540d\u3001\u521b\u4f5c\u8005\u540d\u79f0\u6216\u66f4\u5177\u4f53\u7684\u4e3b\u9898\u3002',
        invalid: '\u8bf7\u8f93\u5165 2-120 \u4e2a\u5b57\u7b26\u7684\u5173\u952e\u8bcd\uff0c\u6216\u6709\u6548\u7684 YouTube \u89c6\u9891\u3001\u64ad\u653e\u5217\u8868\u94fe\u63a5\u3002',
        error: '\u641c\u7d22\u6682\u65f6\u4e0d\u53ef\u7528\uff0c\u8bf7\u91cd\u8bd5\u3002', busy: '\u641c\u7d22\u8bf7\u6c42\u8fc7\u591a\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5\u3002', timeout: '\u641c\u7d22\u8d85\u65f6\uff0c\u8bf7\u91cd\u8bd5\u3002',
        clipboard: '\u8bf7\u4f7f\u7528 Ctrl+V \u6216\u8bbe\u5907\u7684\u7c98\u8d34\u83dc\u5355\u3002', ready: '\u4ece\u4e00\u4e2a\u641c\u7d22\u5f00\u59cb', readyBody: '\u5728\u4e0a\u65b9\u641c\u7d22\u89c6\u9891\uff0c\u6216\u7c98\u8d34\u5df2\u6709\u94fe\u63a5\u3002',
        video: '\u89c6\u9891\u548c\u58f0\u97f3', audio: '\u4ec5\u97f3\u9891', mute: '\u4ec5\u89c6\u9891', quality: '\u89c6\u9891\u753b\u8d28', best: '\u6700\u9ad8\u53ef\u7528\u753b\u8d28', format: '\u97f3\u9891\u683c\u5f0f', bitrate: '\u97f3\u9891\u7801\u7387',
        download: '\u4e0b\u8f7d', downloading: '\u6b63\u5728\u51c6\u5907\u4e0b\u8f7d...', started: '\u5df2\u4ea4\u7ed9\u4e0b\u8f7d\u6d41\u7a0b\uff0c\u8bf7\u5728\u4e0b\u8f7d\u961f\u5217\u6216\u6d4f\u89c8\u5668\u4e2d\u67e5\u770b\u8fdb\u5ea6\u3002',
        sourceNote: '\u53ef\u7528\u753b\u8d28\u53d6\u51b3\u4e8e\u539f\u89c6\u9891\uff0c\u5fc5\u8981\u65f6\u4f1a\u4f7f\u7528\u66f4\u4f4e\u753b\u8d28\u3002', searchNote: '\u641c\u7d22\u4e0d\u6d88\u8017\u4e0b\u8f7d\u79ef\u5206\uff1b\u4e0b\u8f7d\u6309\u8d26\u6237\u5957\u9910\u548c\u79ef\u5206\u89c4\u5219\u6267\u884c\u3002',
        watch: '\u5728 YouTube \u89c2\u770b', change: '\u9009\u62e9\u5176\u4ed6\u89c6\u9891', playlist: '\u64ad\u653e\u5217\u8868\u89c6\u9891', batch: '\u4e0b\u8f7d\u64ad\u653e\u5217\u8868',
        step1: '\u67e5\u627e', step1Body: '\u641c\u7d22\u6807\u9898\u6216\u7c98\u8d34 YouTube \u94fe\u63a5\u3002', step2: '\u9009\u62e9', step2Body: '\u9009\u62e9\u89c6\u9891\u3001\u753b\u8d28\u548c\u97f3\u9891\u683c\u5f0f\u3002', step3: '\u4fdd\u5b58', step3Body: '\u5f00\u59cb\u4e0b\u8f7d\u5e76\u67e5\u770b\u8fdb\u5ea6\u3002',
        related: '\u66f4\u591a YouTube \u5de5\u5177', guide: 'YouTube \u4e0b\u8f7d\u6307\u5357', shorts: 'YouTube Shorts', tools: '\u6240\u6709\u4e0b\u8f7d\u5de5\u5177',
    },
};

const downloadErrors: Record<string, string> = {
    id: 'Tidak dapat menyiapkan unduhan. Coba lagi.',
    en: 'Could not prepare the download. Please try again.', zh: '\u65e0\u6cd5\u51c6\u5907\u4e0b\u8f7d\uff0c\u8bf7\u91cd\u8bd5\u3002',
    de: 'Der Download konnte nicht vorbereitet werden. Bitte erneut versuchen.', es: 'No se pudo preparar la descarga. Inténtalo de nuevo.',
    fr: 'Impossible de préparer le téléchargement. Réessayez.', ja: 'ダウンロードを準備できませんでした。再試行してください。',
    ko: '다운로드를 준비할 수 없습니다. 다시 시도하세요.', ru: 'Не удалось подготовить загрузку. Повторите попытку.',
    th: 'เตรียมดาวน์โหลดไม่ได้ โปรดลองอีกครั้ง', vi: 'Không thể chuẩn bị tải xuống. Vui lòng thử lại.',
};
export const getYouTubeCopy = (lang: string): Copy & { downloadError: string } => ({
    ...(copies[lang] || en), downloadError: downloadErrors[lang] || downloadErrors.en,
});
